CREATE TABLE IF NOT EXISTS voice_channel_sessions (
            id TEXT PRIMARY KEY,
            organization_id TEXT NOT NULL,
            bot_id TEXT NOT NULL,
            contact_id TEXT NOT NULL,
            conversation_id TEXT NOT NULL,
            channel TEXT NOT NULL,
            state TEXT NOT NULL DEFAULT 'listening',
            requested_modality TEXT NOT NULL DEFAULT 'voice',
            active_modality TEXT NOT NULL DEFAULT 'voice',
            turn_taking_mode TEXT NOT NULL DEFAULT 'full_duplex_guarded',
            barge_in_enabled INTEGER NOT NULL DEFAULT 1,
            continuity_mode TEXT NOT NULL DEFAULT 'shared_runtime_memory',
            stt_provider TEXT,
            tts_provider TEXT,
            latest_intent_family TEXT,
            latest_specialist_agent_key TEXT,
            urgency_level TEXT NOT NULL DEFAULT 'normal',
            urgency_score INTEGER NOT NULL DEFAULT 0,
            policy_profile_key TEXT,
            policy_profile_version TEXT,
            handoff_channel TEXT,
            handoff_state TEXT NOT NULL DEFAULT 'none',
            shared_memory_json TEXT NOT NULL DEFAULT '{}',
            metadata_json TEXT NOT NULL DEFAULT '{}',
            started_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            ended_at TEXT,
            FOREIGN KEY (organization_id) REFERENCES organizations(id),
            FOREIGN KEY (bot_id) REFERENCES bots(id),
            FOREIGN KEY (contact_id) REFERENCES contacts(id),
            FOREIGN KEY (conversation_id) REFERENCES conversations(id)
        );
        CREATE INDEX IF NOT EXISTS idx_voice_channel_sessions_org ON voice_channel_sessions(organization_id, bot_id, updated_at DESC);
        CREATE INDEX IF NOT EXISTS idx_voice_channel_sessions_contact ON voice_channel_sessions(contact_id, updated_at DESC);

        CREATE TABLE IF NOT EXISTS voice_channel_turns (
            id TEXT PRIMARY KEY,
            session_id TEXT NOT NULL,
            organization_id TEXT NOT NULL,
            bot_id TEXT NOT NULL,
            contact_id TEXT NOT NULL,
            conversation_id TEXT NOT NULL,
            message_id TEXT,
            linked_voice_note_id TEXT,
            turn_index INTEGER NOT NULL,
            actor TEXT NOT NULL,
            modality TEXT NOT NULL,
            transcript_text TEXT,
            normalized_text TEXT,
            intent_family TEXT,
            urgency_level TEXT,
            urgency_score INTEGER NOT NULL DEFAULT 0,
            requested_human INTEGER NOT NULL DEFAULT 0,
            extracted_entities_json TEXT NOT NULL DEFAULT '{}',
            route_json TEXT NOT NULL DEFAULT '{}',
            policy_json TEXT NOT NULL DEFAULT '{}',
            shared_memory_json TEXT NOT NULL DEFAULT '{}',
            response_json TEXT NOT NULL DEFAULT '{}',
            state TEXT NOT NULL DEFAULT 'completed',
            interruption_reason TEXT,
            audio_render_status TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (session_id) REFERENCES voice_channel_sessions(id),
            FOREIGN KEY (message_id) REFERENCES messages(id),
            FOREIGN KEY (linked_voice_note_id) REFERENCES voice_notes(id)
        );
        CREATE INDEX IF NOT EXISTS idx_voice_channel_turns_session ON voice_channel_turns(session_id, turn_index ASC);
        CREATE INDEX IF NOT EXISTS idx_voice_channel_turns_conversation ON voice_channel_turns(conversation_id, created_at DESC);

        CREATE TABLE IF NOT EXISTS voice_channel_handoffs (
            id TEXT PRIMARY KEY,
            session_id TEXT NOT NULL,
            organization_id TEXT NOT NULL,
            bot_id TEXT NOT NULL,
            contact_id TEXT NOT NULL,
            conversation_id TEXT NOT NULL,
            from_channel TEXT NOT NULL,
            to_channel TEXT NOT NULL,
            reason TEXT NOT NULL,
            summary_text TEXT,
            target_queue TEXT,
            status TEXT NOT NULL DEFAULT 'completed',
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL,
            accepted_at TEXT,
            completed_at TEXT,
            FOREIGN KEY (session_id) REFERENCES voice_channel_sessions(id)
        );
        CREATE INDEX IF NOT EXISTS idx_voice_channel_handoffs_session ON voice_channel_handoffs(session_id, created_at DESC);
