-- 003_voice_channel.sql
-- Cumulative schema slice for WAOS production hardened artifact.

CREATE TABLE IF NOT EXISTS voice_channel_handoffs (
    id TEXT PRIMARY KEY,
    accepted_at TEXT,
    bot_id TEXT,
    completed_at TEXT,
    contact_id TEXT,
    conversation_id TEXT,
    created_at TEXT,
    from_channel TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    organization_id TEXT,
    reason TEXT,
    session_id TEXT,
    status TEXT,
    summary_text TEXT,
    target_queue TEXT,
    to_channel TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS voice_channel_sessions (
    id TEXT PRIMARY KEY,
    active_modality TEXT,
    barge_in_enabled INTEGER NOT NULL DEFAULT 0,
    bot_id TEXT,
    channel TEXT,
    contact_id TEXT,
    continuity_mode TEXT,
    conversation_id TEXT,
    created_at TEXT,
    ended_at TEXT,
    handoff_channel TEXT,
    handoff_state TEXT,
    latest_intent_family TEXT,
    latest_specialist_agent_key TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    organization_id TEXT,
    policy_profile_key TEXT,
    policy_profile_version TEXT,
    requested_modality TEXT,
    shared_memory_json TEXT NOT NULL DEFAULT '{}',
    started_at TEXT,
    state TEXT,
    status TEXT,
    stt_provider TEXT,
    tts_provider TEXT,
    turn_taking_mode TEXT,
    updated_at TEXT,
    urgency_level TEXT,
    urgency_score REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS voice_channel_turns (
    id TEXT PRIMARY KEY,
    actor TEXT,
    audio_render_status TEXT,
    bot_id TEXT,
    contact_id TEXT,
    conversation_id TEXT,
    created_at TEXT,
    extracted_entities_json TEXT NOT NULL DEFAULT '{}',
    intent_family TEXT,
    interruption_reason TEXT,
    linked_voice_note_id TEXT,
    message_id TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    modality TEXT,
    normalized_text TEXT,
    organization_id TEXT,
    policy_json TEXT NOT NULL DEFAULT '{}',
    requested_human TEXT,
    response_json TEXT NOT NULL DEFAULT '{}',
    route_json TEXT NOT NULL DEFAULT '{}',
    session_id TEXT,
    shared_memory_json TEXT NOT NULL DEFAULT '{}',
    state TEXT,
    status TEXT,
    transcript_text TEXT,
    turn_index TEXT,
    updated_at TEXT,
    urgency_level TEXT,
    urgency_score REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS voice_notes (
    id TEXT PRIMARY KEY,
    audio_quality TEXT,
    background_noise_level TEXT,
    bot_id TEXT,
    consent_status TEXT,
    contact_id TEXT,
    conversation_id TEXT,
    created_at TEXT,
    detected_language TEXT,
    diarization_json TEXT NOT NULL DEFAULT '{}',
    emotion TEXT,
    intent TEXT,
    media_expires_at TEXT,
    media_id TEXT,
    media_mime_type TEXT,
    media_sha256 TEXT,
    media_size_bytes INTEGER NOT NULL DEFAULT 0,
    media_url TEXT,
    message_id TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    organization_id TEXT,
    processing_status TEXT,
    reply_mode TEXT,
    segments_json TEXT NOT NULL DEFAULT '{}',
    status TEXT,
    suggested_response_audio_text TEXT,
    suggested_response_text TEXT,
    summary TEXT,
    transcript TEXT,
    transcription_confidence TEXT,
    transcription_source TEXT,
    updated_at TEXT,
    urgency_level TEXT
);

