-- 005_vertical_transactions.sql
-- Cumulative schema slice for WAOS production hardened artifact.

CREATE TABLE IF NOT EXISTS commerce_payments (
    id TEXT PRIMARY KEY,
    amount REAL NOT NULL DEFAULT 0,
    appointment_id TEXT,
    bot_id TEXT,
    cart_recovery_status TEXT,
    checkout_expires_at TEXT,
    client_request_id TEXT,
    confirmation_token_hash TEXT,
    confirmed_at TEXT,
    contact_id TEXT,
    conversation_id TEXT,
    correlation_id TEXT,
    created_at TEXT,
    crm_lead_id TEXT,
    currency TEXT,
    external_payment_id TEXT,
    integration_id TEXT,
    last_reconciliation_error TEXT,
    locked_at TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    next_reconciliation_at TEXT,
    operational_status TEXT,
    organization_id TEXT,
    paid_at TEXT,
    payment_link_status TEXT,
    payment_link_url TEXT,
    preview_execution_id TEXT,
    provider TEXT,
    provider_reference TEXT,
    provider_request_id TEXT,
    provider_response_id TEXT,
    provider_response_json TEXT NOT NULL DEFAULT '{}',
    provider_status TEXT,
    provider_status_code INTEGER NOT NULL DEFAULT 0,
    receipt_sent_at TEXT,
    reconciled_at TEXT,
    reconciliation_attempts INTEGER NOT NULL DEFAULT 0,
    reconciliation_status TEXT,
    reminder_scheduled_at TEXT,
    send_receipt_on_confirm TEXT,
    status TEXT,
    title TEXT,
    tool_execution_idempotency_key TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS vertical_transactions (
    id TEXT PRIMARY KEY,
    bot_id TEXT,
    created_at TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    organization_id TEXT,
    status TEXT,
    updated_at TEXT
);

