CREATE TABLE IF NOT EXISTS growth_os_control_states (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    bot_id TEXT NOT NULL UNIQUE,
    is_enabled INTEGER NOT NULL DEFAULT 1,
    scheduler_enabled INTEGER NOT NULL DEFAULT 1,
    scheduler_mode TEXT NOT NULL DEFAULT 'recommend',
    cycle_interval_minutes INTEGER NOT NULL DEFAULT 30,
    default_goals_json TEXT NOT NULL DEFAULT '[]',
    max_targets INTEGER NOT NULL DEFAULT 5,
    auto_execute INTEGER NOT NULL DEFAULT 0,
    include_suppressed INTEGER NOT NULL DEFAULT 0,
    scorecard_window TEXT NOT NULL DEFAULT '28d',
    prioritize_specialist INTEGER NOT NULL DEFAULT 1,
    prioritize_tools INTEGER NOT NULL DEFAULT 1,
    prioritize_handoffs INTEGER NOT NULL DEFAULT 1,
    prioritize_playbooks INTEGER NOT NULL DEFAULT 1,
    contact_focus_hours INTEGER NOT NULL DEFAULT 72,
    latest_run_id TEXT,
    last_started_at TEXT,
    last_completed_at TEXT,
    next_scheduled_at TEXT,
    last_status TEXT NOT NULL DEFAULT 'idle',
    last_summary_json TEXT NOT NULL DEFAULT '{}',
    config_json TEXT NOT NULL DEFAULT '{}',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_growth_os_control_states_due ON growth_os_control_states(is_enabled, scheduler_enabled, next_scheduled_at);
