import { test, expect } from '@playwright/test';
import { apiRequest, buildStripeSignature, chooseOrganization, currentCodeFromSecret, login, readSeedSecrets, submitLogin } from './helpers.real';
const seeds = readSeedSecrets();
async function loginAsRealAdmin(page: import('@playwright/test').Page) {
  await login(page, seeds.mfa_user_email, seeds.mfa_user_password);
  await submitLogin(page);
  await expect(page.getByText(/Confirma con MFA/i)).toBeVisible();
  await page.getByLabel('Código MFA').fill(currentCodeFromSecret(seeds.mfa_user_secret));
  await submitLogin(page);
  await expect(page).toHaveURL(/\/organizations/);
}
test('@critical valida multi-org real, agenda real y pago real reflejado en UI', async ({ page, context, request }) => {
  await loginAsRealAdmin(page);
  await chooseOrganization(page, 'org_2');
  await page.goto('/agenda');
  await expect(page.getByText(/Seguimiento premium/i)).toBeVisible();
  await expect(page.getByText(/Demo comercial/i)).toHaveCount(0);
  await page.goto('/organizations');
  await chooseOrganization(page, 'org_1');
  await page.goto('/agenda');
  await expect(page.getByText(/Demo comercial/i)).toBeVisible();
  let response = await apiRequest(request, context, 'POST', '/api/v1/appointments/apt_org1/confirm', { reason: '' });
  expect(response.ok()).toBeTruthy();
  await page.reload();
  await expect(page.getByText('confirmed')).toBeVisible();
  response = await apiRequest(request, context, 'POST', '/api/v1/appointments/apt_org1/reschedule', { scheduled_for: '2026-04-17T16:30:00Z' });
  expect(response.ok()).toBeTruthy();
  await page.reload();
  await expect(page.getByText(/2026-04-17/i)).toBeVisible();
  response = await apiRequest(request, context, 'POST', '/api/v1/appointments/apt_org1/no-show', { reason: '' });
  expect(response.ok()).toBeTruthy();
  await page.reload();
  await expect(page.getByText('no_show')).toBeVisible();
  response = await apiRequest(request, context, 'POST', '/api/v1/appointments/apt_org1/cancel', { reason: 'Cliente reprograma después' });
  expect(response.ok()).toBeTruthy();
  await page.reload();
  await expect(page.getByText('cancelled')).toBeVisible();
  response = await apiRequest(request, context, 'POST', '/api/v1/sales/payments', { organization_id: 'org_1', bot_id: 'bot_1', conversation_id: 'conv_1', contact_id: 'ct_1', title: 'Pago demo browser real', amount: 1499, currency: 'MXN', appointment_id: 'apt_org1', metadata: { source: 'playwright-real' } });
  expect(response.ok()).toBeTruthy();
  const payment = await response.json();
  expect(payment.checkout_url || payment.payment_link_url).toBeTruthy();
  await page.goto('/revenue');
  await expect(page.getByText(String(payment.id))).toBeVisible();
  await expect(page.getByText(/pending|open/i)).toBeVisible();
  const webhookPayload = JSON.stringify({ type: 'checkout.session.completed', data: { object: { id: payment.external_payment_id || `cs_fake_${payment.id}`, payment_intent: payment.provider_reference || `pi_fake_${payment.id}`, client_reference_id: payment.id, metadata: { payment_id: payment.id, appointment_id: 'apt_org1' } } } });
  const signature = buildStripeSignature(webhookPayload, 'whsec_123456789');
  const webhookResponse = await request.post('http://127.0.0.1:4100/webhooks/stripe', { data: webhookPayload, headers: { 'content-type': 'application/json', 'stripe-signature': signature } });
  expect(webhookResponse.ok()).toBeTruthy();
  await page.reload();
  await expect(page.getByText(/paid/i)).toBeVisible();
  await page.goto('/agenda');
  await expect(page.getByText(/paid|matched/i)).toBeVisible();
  const forbidden = await apiRequest(request, context, 'GET', '/api/v1/appointments?organization_id=org_3');
  expect(forbidden.status()).toBe(403);
});
