import { test, expect } from '@playwright/test';
import { apiRequest, currentCodeFromSecret, currentCodeFromUri, getCookieValue, login, readSeedSecrets, setBrokenAccessTokenButKeepRefresh, submitLogin } from './helpers.real';
const seeds = readSeedSecrets();
test('@critical corre login real con onboarding MFA, recovery codes y logout', async ({ page, context, request }) => {
  await page.goto('/login');
  await page.getByLabel('Correo').fill('sso@enterprise.test');
  await page.getByLabel('Correo').blur();
  await expect(page.getByRole('link', { name: /Entrar con SSO/i })).toBeVisible();
  await login(page, seeds.owner_email, seeds.owner_password);
  await submitLogin(page);
  await expect(page.getByText(/Activa MFA para continuar/i)).toBeVisible();
  const provisioningUri = (await page.getByText(/otpauth:\/\//i).textContent()) || '';
  expect(provisioningUri).toContain('otpauth://');
  const setupCode = currentCodeFromUri(provisioningUri);
  await page.getByLabel('Código inicial de MFA').fill(setupCode);
  await submitLogin(page);
  await expect(page.getByText(/Confirma con MFA/i)).toBeVisible();
  await page.getByLabel('Código MFA').fill(currentCodeFromUri(provisioningUri));
  await submitLogin(page);
  await expect(page).toHaveURL(/\/organizations/);
  const recoveryResponse = await apiRequest(request, context, 'POST', '/api/v1/security/mfa/recovery-codes/regenerate', { code: currentCodeFromUri(provisioningUri) });
  expect(recoveryResponse.ok()).toBeTruthy();
  const recoveryBody = await recoveryResponse.json();
  expect(Array.isArray(recoveryBody.recovery_codes)).toBeTruthy();
  expect(recoveryBody.recovery_codes.length).toBeGreaterThan(0);
  await page.getByRole('button', { name: /Salir/i }).click();
  await expect(page).toHaveURL(/\/login/);
});
test('@critical ejecuta challenge MFA real y refresh token real con cookies reales', async ({ page, context }) => {
  await login(page, seeds.mfa_user_email, seeds.mfa_user_password);
  await submitLogin(page);
  await expect(page.getByText(/Confirma con MFA/i)).toBeVisible();
  await page.getByLabel('Código MFA').fill(currentCodeFromSecret(seeds.mfa_user_secret));
  await submitLogin(page);
  await expect(page).toHaveURL(/\/organizations/);
  const refreshCookie = await getCookieValue(context, 'waos_refresh_token');
  expect(refreshCookie).toBeTruthy();
  await setBrokenAccessTokenButKeepRefresh(context);
  await page.goto('/agenda');
  await expect(page.getByText('Agenda')).toBeVisible();
  await expect(page.getByText(/Demo comercial/i)).toBeVisible();
});
