import { createSecretAction, rotateSecretAction } from "../actions";
import { Badge, DataTable, PermissionGate, Section, Shell, StatCard } from "../components";
import ConfirmSubmitButton from "../components/ConfirmSubmitButton";
import CreateSecretForm from "../components/CreateSecretForm";
import { canManageSecrets, canRotateSecrets, roleLabel } from "../lib/permissions";
import { getCurrentOrganizationId, getSession } from "../lib/session";
import { formatNumber, safeText } from "../lib/ui";
import { getBots, getSecrets } from "../lib/waos";

export default async function SecretsPage() {
  const [session, secrets, bots, organizationId] = await Promise.all([getSession(), getSecrets(), getBots(), getCurrentOrganizationId()]);
  const role = session?.user.global_role;
  return <Shell title="Claves y secretos" subtitle="Un lugar controlado para revisar qué clave existe, cuándo se tocó por última vez y cuándo conviene rotarla."><div className="grid gap-4 md:grid-cols-3"><StatCard label="Secretos" value={formatNumber(secrets.length)} hint="Claves registradas" icon="shield" tone="blue" /><StatCard label="Bots" value={formatNumber(bots.length)} hint="Posibles consumidores" icon="bot" tone="green" /><StatCard label="Por rotar" value={formatNumber(secrets.filter((item) => item.rotation_due).length)} hint="Necesitan atención" icon="refresh" tone="gold" /></div><div className="mb-4 text-sm text-slate-300">Tu rol visible ahora es {roleLabel(role)}.</div><Section title="Secretos guardados" subtitle="Revisa nombre, uso y estado sin exponer valores sensibles." icon="shield"><DataTable columns={["Nombre", "Alcance", "Última rotación", "Acciones"]} rows={secrets.map((item) => [safeText(item.key_name || item.name), <Badge key={`${item.id}-scope`} tone={safeText(item.scope).toLowerCase() === "bot" ? "sky" : "slate"}>{safeText(item.scope, "tenant")}</Badge>, safeText(item.updated_at || item.last_rotated_at), <PermissionGate allowed={canRotateSecrets(role)} fallback={<span className="mono-pill">Sin permiso de rotacion</span>}><form key={item.id} action={rotateSecretAction}><input type="hidden" name="secret_id" value={item.id} /><input type="hidden" name="organization_id" value={organizationId || ""} /><input type="hidden" name="scope" value={item.scope || "tenant"} /><input type="hidden" name="key_name" value={item.key_name || item.name || ""} /><input type="hidden" name="bot_id" value={item.bot_id || ""} /><input type="hidden" name="redirect_to" value="/secrets" /><input type="hidden" name="secret_value" value="rotation-required" /><ConfirmSubmitButton message="¿Seguro que quieres rotar este secreto?">Rotar</ConfirmSubmitButton></form></PermissionGate>])} /></Section><Section title="Crear nueva clave" subtitle="Deja lista una clave nueva cuando necesites conectar un servicio o renovar acceso." icon="check"><PermissionGate allowed={canManageSecrets(role)} fallback={<div className="text-sm text-slate-300">Tu rol puede revisar secretos pero no crear nuevas claves desde esta pantalla.</div>}><CreateSecretForm action={createSecretAction} organizationId={organizationId || ""} bots={bots.map((bot) => ({ id: String(bot.id), name: safeText(bot.name, bot.id) }))} /></PermissionGate></Section></Shell>;
}
