-- voice as a first-class native channel
CREATE TABLE IF NOT EXISTS voice_channel_sessions (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    bot_id TEXT NOT NULL,
    contact_id TEXT NOT NULL,
    conversation_id TEXT NOT NULL,
    channel TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'listening',
    requested_modality TEXT NOT NULL DEFAULT 'voice',
    active_modality TEXT NOT NULL DEFAULT 'voice',
    turn_taking_mode TEXT NOT NULL DEFAULT 'full_duplex_guarded',
    barge_in_enabled INTEGER NOT NULL DEFAULT 1,
    continuity_mode TEXT NOT NULL DEFAULT 'shared_runtime_memory',
    stt_provider TEXT,
    tts_provider TEXT,
    latest_intent_family TEXT,
    latest_specialist_agent_key TEXT,
    urgency_level TEXT NOT NULL DEFAULT 'normal',
    urgency_score INTEGER NOT NULL DEFAULT 0,
    policy_profile_key TEXT,
    policy_profile_version TEXT,
    handoff_channel TEXT,
    handoff_state TEXT NOT NULL DEFAULT 'none',
    shared_memory_json TEXT NOT NULL DEFAULT '{}',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    started_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    ended_at TEXT
);
