import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
function read(relativePath: string) { return fs.readFileSync(path.join(root, relativePath), "utf8"); }
test("/bot-studio is AI Command Center and hides manual create", () => { const page=read("app/bot-studio/page.tsx"); assert.match(page,/WAOS AI Command Center/); assert.match(page,/AiCommandCenter/); assert.doesNotMatch(page,/Crear desde cero/); assert.doesNotMatch(page,/Rutas canónicas/); assert.doesNotMatch(page,/create\/context/); });
test("AI Command Center prompt has required controls", () => { const prompt=read("features/ai-command-center/AiCommandPrompt.tsx"); assert.match(prompt,/Describe el negocio, ciudad, servicios, objetivo, restricciones y qué debe lograr WhatsApp/); assert.match(prompt,/Construir agente con IA/); for (const field of ["auto_generate_knowledge","auto_generate_templates","auto_generate_tools","auto_run_simulations","auto_autofix","auto_prepare_go_live","auto_apply"]) assert.match(prompt,new RegExp(field)); for (const intensity of ["conservative","balanced","aggressive","savage","godmode"]) assert.match(prompt,new RegExp(intensity)); });
test("manual create routes redirect unless feature flag is enabled", () => { const page=read("app/bot-studio/[mode]/[[...slug]]/page.tsx"); assert.match(page,/NEXT_PUBLIC_ENABLE_MANUAL_BOT_CREATE === "true"/); assert.match(page,/if \(!MANUAL_ENABLED\)/); assert.match(page,/redirect\(`\/bot-studio\$\{query\}`\)/); assert.match(page,/AI Generated Setup Review/); });
test("AI Command Center consumes real SSE and supports completed_partial", () => { const hook=read("features/ai-command-center/useAiWorkflowStream.ts"); const timeline=read("features/ai-command-center/AiRunTimeline.tsx"); assert.match(hook,/new EventSource/); assert.match(hook,/workflow\.completed_partial/); assert.doesNotMatch(hook,/setTimeout/); assert.match(timeline,/completed_partial/); });
test("legacy AiSetupAssistant exposes guarded progress copy without fake timeout simulation", () => { const assistant=read("features/bot-studio/create/AiSetupAssistant.tsx"); assert.match(assistant,/const AUTOPILOT_PROGRESS_MESSAGES/); assert.match(assistant,/Detectando industria\.\.\./); assert.match(assistant,/Generando setup completo\.\.\./); assert.match(assistant,/Validando\.\.\./); assert.match(assistant,/onAutopilot\(\{ userDescription: description, intensity: "savage" \}\)/); assert.doesNotMatch(assistant,/setTimeout/); assert.match(assistant,/no simula etapas/); });
test("frontend AI workflow proxy routes exist and preserve streaming", () => { for (const route of ["app/api/ai/bot-autopilot/route.ts","app/api/ai/workflows/[runId]/route.ts","app/api/ai/workflows/[runId]/events/route.ts","app/api/ai/workflows/[runId]/simulate/route.ts","app/api/ai/workflows/[runId]/go-live-readiness/route.ts","app/api/ai/workflows/[runId]/prepare-apply/route.ts","app/api/ai/workflows/[runId]/apply/route.ts","app/api/ai/workflows/[runId]/prepare-canary/route.ts"]) assert.ok(fs.existsSync(path.join(root,route)), route); const events=read("app/api/ai/workflows/[runId]/events/route.ts"); assert.match(events,/text\/event-stream/); assert.match(events,/ReadableStream/); });
