from __future__ import annotations

from .schema_sql import apply_schema_sql, load_schema_sql

RUNTIME_SCHEMA_SQL_FILES = [
    "001_backend_runtime.sql",
    "002_talent.sql",
    "007_growth_os_control_state.sql",
    "003_voice_channel.sql",
    "005_vertical_transactions.sql",
    "004_vertical_domain.sql",
    "006_db_runtime_tables.sql",
    "008_runtime_indexes.sql",
]

VOICE_CHANNEL_SCHEMA_SQL = load_schema_sql("runtime", "003_voice_channel.sql")

DB_RUNTIME_COLUMN_ENSURES = [('secret_entries', 'value_encrypted', 'TEXT'),
 ('secret_entries', 'encryption_version', "TEXT NOT NULL DEFAULT 'v1'"),
 ('secret_entries', 'metadata_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('secret_entries', 'expires_at', 'TEXT'),
 ('secret_entries', 'last_accessed_at', 'TEXT'),
 ('secret_entries', 'last_access_actor_type', 'TEXT'),
 ('secret_entries', 'last_access_actor_id', 'TEXT'),
 ('outbox_messages', 'provider_message_id', 'TEXT'),
 ('outbox_messages', 'provider_status_code', 'INTEGER'),
 ('outbox_messages', 'provider_response_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('outbox_messages', 'next_attempt_at', 'TEXT'),
 ('outbox_messages', 'priority', 'INTEGER NOT NULL DEFAULT 50'),
 ('outbox_messages', 'locked_at', 'TEXT'),
 ('outbox_messages', 'governance_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('automation_jobs', 'priority', 'INTEGER NOT NULL DEFAULT 50'),
 ('appointments', 'external_id', 'TEXT'),
 ('appointments', 'provider', 'TEXT'),
 ('appointments', 'provider_payload_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('appointments', 'integration_id', 'TEXT'),
 ('appointments', 'synced_at', 'TEXT'),
 ('appointments', 'reminder_scheduled_at', 'TEXT'),
 ('appointments', 'confirmed_at', 'TEXT'),
 ('appointments', 'cancelled_at', 'TEXT'),
 ('appointments', 'no_show_at', 'TEXT'),
 ('appointments', 'followup_status', "TEXT NOT NULL DEFAULT 'pending'"),
 ('appointments', 'followup_sent_at', 'TEXT'),
 ('appointments', 'rescheduled_from_appointment_id', 'TEXT'),
 ('mfa_factors', 'secret_encrypted', 'TEXT'),
 ('mfa_factors', 'secret_masked', 'TEXT'),
 ('mfa_factors', 'recovery_codes_json', "TEXT NOT NULL DEFAULT '[]'"),
 ('mfa_factors', 'revoked_at', 'TEXT'),
 ('audit_logs', 'request_id', 'TEXT'),
 ('audit_logs', 'session_id', 'TEXT'),
 ('audit_logs', 'ip_address', 'TEXT'),
 ('audit_logs', 'user_agent', 'TEXT'),
 ('audit_logs', 'severity', "TEXT NOT NULL DEFAULT 'info'"),
 ('audit_logs', 'trace_id', 'TEXT'),
 ('auth_sessions', 'refresh_token_family_id', 'TEXT'),
 ('auth_sessions', 'max_idle_at', 'TEXT'),
 ('auth_sessions', 'idle_timeout_minutes', 'INTEGER NOT NULL DEFAULT 120'),
 ('auth_sessions', 'last_authenticated_at', 'TEXT'),
 ('auth_sessions', 'refresh_token_last_rotated_at', 'TEXT'),
 ('auth_sessions', 'refresh_token_reuse_detected_at', 'TEXT'),
 ('organization_security_policies', 'session_idle_timeout_minutes', 'INTEGER NOT NULL DEFAULT 120'),
 ('organization_security_policies', 'step_up_window_minutes', 'INTEGER NOT NULL DEFAULT 15'),
 ('organization_security_policies', 'max_sessions_per_user', 'INTEGER NOT NULL DEFAULT 5'),
 ('organization_security_policies', 'require_dual_approval_releases', 'INTEGER NOT NULL DEFAULT 1'),
 ('mfa_factors', 'label', 'TEXT'),
 ('whatsapp_flows', 'remote_flow_id', 'TEXT'),
 ('whatsapp_flows', 'remote_status', "TEXT NOT NULL DEFAULT 'not_synced'"),
 ('whatsapp_flows', 'remote_details_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('whatsapp_flows', 'fallback_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('whatsapp_flows', 'runtime_config_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('whatsapp_flows', 'current_version_id', 'TEXT'),
 ('whatsapp_flows', 'published_version_id', 'TEXT'),
 ('whatsapp_flows', 'runtime_endpoint', 'TEXT'),
 ('whatsapp_flows', 'remote_last_synced_at', 'TEXT'),
 ('whatsapp_flows', 'remote_last_published_at', 'TEXT'),
 ('whatsapp_flows', 'last_sync_error', 'TEXT'),
 ('whatsapp_numbers', 'quality_rating', "TEXT NOT NULL DEFAULT 'unknown'"),
 ('whatsapp_numbers', 'quality_status', "TEXT NOT NULL DEFAULT 'unknown'"),
 ('whatsapp_numbers', 'throughput_tier', "TEXT NOT NULL DEFAULT 'standard'"),
 ('whatsapp_numbers', 'provider_degraded_until', 'TEXT'),
 ('whatsapp_numbers', 'last_health_check_at', 'TEXT'),
 ('whatsapp_numbers', 'last_provider_error_code', 'TEXT'),
 ('whatsapp_numbers', 'last_provider_error_at', 'TEXT'),
 ('integration_connections', 'credential_status', "TEXT NOT NULL DEFAULT 'unknown'"),
 ('integration_connections', 'last_error', 'TEXT'),
 ('integration_connections', 'last_provider_event_at', 'TEXT'),
 ('integration_connections', 'last_provider_status_code', 'INTEGER'),
 ('integration_connections', 'auto_sync_enabled', 'INTEGER NOT NULL DEFAULT 0'),
 ('integration_connections', 'sync_frequency_minutes', 'INTEGER NOT NULL DEFAULT 30'),
 ('integration_connections', 'next_sync_at', 'TEXT'),
 ('integration_connections', 'retry_count', 'INTEGER NOT NULL DEFAULT 0'),
 ('integration_connections', 'last_success_at', 'TEXT'),
 ('integration_connections', 'locked_at', 'TEXT'),
 ('commerce_payments', 'provider', 'TEXT'),
 ('commerce_payments', 'integration_id', 'TEXT'),
 ('commerce_payments', 'provider_reference', 'TEXT'),
 ('commerce_payments', 'external_payment_id', 'TEXT'),
 ('commerce_payments', 'provider_status', 'TEXT'),
 ('commerce_payments', 'provider_status_code', 'INTEGER'),
 ('commerce_payments', 'provider_response_json', "TEXT NOT NULL DEFAULT '{}'"),
 ('commerce_payments', 'checkout_expires_at', 'TEXT'),
 ('commerce_payments', 'paid_at', 'TEXT'),
 ('commerce_payments', 'appointment_id', 'TEXT'),
 ('commerce_payments', 'reconciliation_status', "TEXT NOT NULL DEFAULT 'pending'"),
 ('commerce_payments', 'reconciled_at', 'TEXT'),
 ('commerce_payments', 'next_reconciliation_at', 'TEXT'),
 ('commerce_payments', 'reconciliation_attempts', 'INTEGER NOT NULL DEFAULT 0'),
 ('commerce_payments', 'last_reconciliation_error', 'TEXT'),
 ('commerce_payments', 'locked_at', 'TEXT'),
 ('appointments', 'payment_id', 'TEXT'),
 ('appointments', 'payment_status', 'TEXT'),
 ('appointments', 'reconciliation_status', 'TEXT'),
 ('executive_reports', 'pdf_path', 'TEXT'),
 ('executive_reports', 'pdf_filename', 'TEXT'),
 ('executive_reports', 'pdf_generated_at', 'TEXT'),
 ('executive_reports', 'updated_at', 'TEXT'),
 ('report_generation_jobs', 'priority', 'INTEGER NOT NULL DEFAULT 50'),
 ('report_generation_jobs', 'locked_at', 'TEXT'),
 ('voice_notes', 'processing_status', "TEXT NOT NULL DEFAULT 'completed'")]


def apply_runtime_schema_ownership_migration(conn, ensure_column) -> None:
    for filename in RUNTIME_SCHEMA_SQL_FILES:
        apply_schema_sql(conn, "runtime", filename)
    for table, column, definition in DB_RUNTIME_COLUMN_ENSURES:
        ensure_column(conn, table, column, definition)
