from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
from typing import Any


def _deep_merge(base: Any, updates: Any) -> Any:
    if isinstance(base, dict) and isinstance(updates, dict):
        merged = deepcopy(base)
        for key, value in updates.items():
            if key in merged and isinstance(merged[key], dict) and isinstance(value, dict):
                merged[key] = _deep_merge(merged[key], value)
            else:
                merged[key] = deepcopy(value)
        return merged
    return deepcopy(updates)


_GLOBAL_REQUIRED_PHRASES = [
    "te sigo",
    "si la pregunta viene rara, igual te la aterrizo",
    "te lo aterrizo a tu caso",
]

_GLOBAL_FALLBACK_NOTE = "Si la pregunta viene rara, en broma o medio fuera de tema, igual te sigo y la aterrizamos al negocio."

_GLOBAL_CONTINUITY_RULES = [
    "nunca quedarse seco ante bromas, preguntas raras o cambios bruscos de tema",
    "usar humor ligero cuando sume, sin sonar payaso ni poco serio",
    "validar el momento y luego reencauzar la conversacion al negocio",
    "cerrar siempre con una pregunta util o siguiente paso",
]


def _merge_unique_list(existing: list[Any] | None, additions: list[Any]) -> list[Any]:
    merged: list[Any] = list(existing or [])
    for item in additions:
        if item not in merged:
            merged.append(deepcopy(item))
    return merged


def _apply_global_conversation_defaults(profile: dict[str, Any]) -> dict[str, Any]:
    enriched = deepcopy(profile)
    behavior = enriched.setdefault("behavior", {})
    behavior["humor_policy"] = behavior.get("humor_policy") or "light_contextual"
    behavior["strange_question_policy"] = behavior.get("strange_question_policy") or "respond_validate_reframe_sell_move"
    behavior["required_phrases"] = _merge_unique_list(behavior.get("required_phrases"), _GLOBAL_REQUIRED_PHRASES)
    fallback_message = (behavior.get("fallback_message") or "Te ayudo con gusto.").strip()
    if _GLOBAL_FALLBACK_NOTE not in fallback_message:
        behavior["fallback_message"] = f"{fallback_message} {_GLOBAL_FALLBACK_NOTE}".strip()

    bot_playbook = enriched.setdefault("bot_playbook", {})
    bot_playbook["must_do"] = _merge_unique_list(bot_playbook.get("must_do"), _GLOBAL_CONTINUITY_RULES)
    bot_playbook["must_ask"] = _merge_unique_list(bot_playbook.get("must_ask"), ["que parte del negocio se esta atorando mas", "si quiere que se lo aterrice a su caso"])
    bot_playbook["style"] = _merge_unique_list(bot_playbook.get("style"), ["humor ligero", "manejo de preguntas raras", "reencuadre comercial"])
    return enriched


def _load_vertical_portfolio_updates() -> dict[str, dict[str, Any]]:
    path = Path(__file__).resolve().parent / "data" / "vertical_portfolio_updates.json"
    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {str(item.get("id")): item for item in payload.get("verticals", []) if item.get("id")}


def _apply_portfolio_updates(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    updates = _load_vertical_portfolio_updates()
    merged_items: list[dict[str, Any]] = []
    seen: set[str] = set()
    for item in items:
        key = str(item.get("id") or "")
        patch = updates.get(key)
        merged_items.append(_deep_merge(item, patch) if patch else deepcopy(item))
        seen.add(key)
    for key, patch in updates.items():
        if key not in seen:
            merged_items.append(deepcopy(patch))
    return merged_items

_VERTICALS: list[dict[str, Any]] = [
    {
        "id": "fitness",
        "name": "WAOS Fitness",
        "short_name": "Fitness & entrenamiento",
        "description": "Convierte preguntas repetitivas en altas, asistencia y permanencia.",
        "problem": "Muchos leads preguntan por planes, horarios, sedes y coaches, pero pocos se inscriben porque nadie filtra, sigue y reactiva con metodo.",
        "subverticals": ["gym tradicional", "boxeo", "MMA", "pilates", "yoga", "running clubs", "calistenia", "taekwondo", "jiu-jitsu", "cross training", "spinning", "funcional", "natacion", "danza fitness"],
        "objects": ["clases", "cupos", "coach", "membresia", "asistencia", "renovacion"],
        "flows": ["lead -> clase muestra", "evaluacion -> inscripcion", "ausencia -> recuperacion", "membresia -> renovacion"],
        "kpis": ["show rate", "trial to signup", "asistencia", "churn", "reactivacion"],
        "recommended_integrations": ["whatsapp", "google_calendar", "payments", "crm"],
        "default_services": ["clase muestra", "evaluacion inicial", "membresia mensual", "personal training", "nutricion"],
        "default_faqs": [
            {"q": "¿Que plan me conviene?", "a": "Te guiamos segun tu objetivo, nivel y frecuencia ideal."},
            {"q": "¿Tienen horarios y sedes?", "a": "Si, podemos compartir horarios, sedes y coaches disponibles."},
            {"q": "¿Puedo agendar una clase muestra?", "a": "Si, el bot puede proponerte horario y dejar apartada tu clase muestra."},
            {"q": "¿Manejan congelamiento o renovacion?", "a": "Si, podemos explicarte condiciones de freeze, renovacion y asistencia."},
        ],
        "behavior": {
            "tone": "enfocado y motivador",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "alta",
            "offer_promotions_when": "after_goal_detected",
            "escalate_when": ["lesion", "reclamo", "cambio de coach", "tema medico"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": False,
            "auto_send_images": True,
            "bot_mode": "captacion_y_reactivacion",
            "active_channels": ["whatsapp", "webchat", "instagram_dm"],
            "forbidden_topics": ["diagnosticos medicos", "promesas fisicas garantizadas"],
            "required_phrases": ["te recomiendo el plan segun tu objetivo", "puedo ayudarte a agendar tu clase muestra"],
            "fallback_message": "Te ayudo a elegir plan, ver horarios o apartar clase muestra. ¿Que objetivo tienes hoy?",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 90, "max_attempts": 2, "message_template": "Solo dando seguimiento. ¿Quieres que te recomiende plan u horario segun tu objetivo?"},
            {"type": "post_quote", "delay_minutes": 720, "max_attempts": 2, "message_template": "¿Quieres que te reserve tu clase muestra o te comparta el plan que mejor encaja contigo?"},
            {"type": "reactivation", "delay_minutes": 10080, "max_attempts": 2, "message_template": "Te extrañamos. Si quieres retomar, te ayudo con horario, coach o plan de regreso."},
        ],
        "templates": [
            {"template_key": "lead_capture", "title": "Captacion fitness", "content": "¡Hola! Soy {{bot_name}} de {{business_name}}. Te ayudo a encontrar el mejor plan segun tu objetivo, nivel y horario ideal.", "variables": ["bot_name", "business_name"]},
            {"template_key": "class_reminder", "title": "Recordatorio de clase", "content": "Te recuerdo tu clase de {{service_name}} el {{date}} a las {{time}}. Si necesitas moverla, te ayudo.", "variables": ["service_name", "date", "time"]},
            {"template_key": "post_trial_followup", "title": "Seguimiento post trial", "content": "¿Como te sentiste en tu clase muestra? Si quieres, hoy mismo te recomiendo el plan ideal y te ayudo a inscribirte.", "variables": []},
            {"template_key": "absence_recovery", "title": "Recuperacion de ausencia", "content": "Notamos que no pudiste venir. ¿Quieres que te proponga nuevo horario para no perder ritmo?", "variables": []},
            {"template_key": "reactivation_offer", "title": "Reactivacion", "content": "Tenemos opciones para que regreses con buen ritmo. ¿Prefieres horario matutino, vespertino o fin de semana?", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["agendar", "reactivar", "upsell"],
            "policies": ["No prometer resultados fisicos garantizados", "Escalar lesiones o temas medicos a humano"],
            "can_say": ["planes", "horarios", "sedes", "coaches", "promociones", "agendar"],
            "cannot_say": ["diagnosticos medicos", "rutinas clinicas", "promesas de transformacion"],
            "whatsapp_flows": ["clase_muestra", "recomendacion_plan", "reactivacion_alumno", "renovacion_membresia"],
            "appointment_duration_minutes": 45,
            "handoff_keywords": ["lesion", "molestia", "reclamo", "cancelacion"],
            "high_score_threshold": 75,
        },
    },
    {
        "id": "dental",
        "name": "WAOS Dental",
        "short_name": "Clinicas dentales",
        "description": "Mueve pacientes desde valoracion hasta tratamiento completo.",
        "problem": "Las clinicas pierden valor cuando responden tarde, no estructuran la valoracion inicial y no persiguen tratamientos no cerrados.",
        "subverticals": ["odontologia general", "ortodoncia", "alineadores", "implantologia", "estetica dental", "endodoncia", "periodoncia", "odontopediatria", "rehabilitacion oral", "cirugia dental"],
        "objects": ["valoracion", "diagnostico", "tratamiento por fases", "presupuesto", "anticipo", "recall"],
        "flows": ["urgencia vs valoracion", "valoracion -> presupuesto", "tratamiento -> seguimiento", "recall -> control"],
        "kpis": ["show rate a valoracion", "aceptacion de tratamiento", "ticket por tratamiento", "recall"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "crm"],
        "default_services": ["valoracion inicial", "limpieza", "radiografia", "ortodoncia", "implantes"],
        "default_faqs": [
            {"q": "¿Es urgencia o valoracion?", "a": "Podemos clasificar si necesitas atencion inmediata o una valoracion programada."},
            {"q": "¿Pueden darme rango de precio?", "a": "Si, el bot puede compartir un rango orientativo y explicarte que el cierre depende de la valoracion."},
            {"q": "¿Se puede financiar?", "a": "Podemos explicarte opciones de anticipo, fases y financiamiento si aplica."},
            {"q": "¿Dan seguimiento al tratamiento?", "a": "Si, recordamos citas, controles y seguimientos por fases."},
        ],
        "behavior": {
            "tone": "claro y tranquilizador",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "media",
            "offer_promotions_when": "after_assessment_booked",
            "escalate_when": ["dolor fuerte", "sangrado", "urgencia", "contraindicacion"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": False,
            "auto_send_images": False,
            "bot_mode": "valoracion_y_cierre",
            "active_channels": ["whatsapp", "webchat"],
            "forbidden_topics": ["diagnostico clinico definitivo por chat", "prescripciones"],
            "required_phrases": ["la valoracion define el plan ideal", "si es una urgencia te canalizo de inmediato"],
            "fallback_message": "Te ayudo a distinguir si es urgencia o valoracion y a agendar con el especialista correcto.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 120, "max_attempts": 2, "message_template": "¿Quieres que te ayude a apartar tu valoracion o a resolver si tu caso es urgencia?"},
            {"type": "post_quote", "delay_minutes": 1440, "max_attempts": 2, "message_template": "Quedo pendiente por si quieres retomar tu plan de tratamiento o resolver dudas antes de avanzar."},
            {"type": "reactivation", "delay_minutes": 43200, "max_attempts": 1, "message_template": "Te recordamos tu siguiente limpieza o control. Si quieres, te ayudo a agendar."},
        ],
        "templates": [
            {"template_key": "assessment_booking", "title": "Agendar valoracion", "content": "Te ayudo a apartar tu valoracion con {{specialist}}. ¿Prefieres {{date_option_1}} o {{date_option_2}}?", "variables": ["specialist", "date_option_1", "date_option_2"]},
            {"template_key": "urgency_triage", "title": "Triage dental", "content": "Para orientarte mejor, dime si hay dolor fuerte, inflamacion, sangrado o trauma reciente.", "variables": []},
            {"template_key": "treatment_followup", "title": "Seguimiento tratamiento", "content": "Te escribimos para dar continuidad a tu tratamiento. ¿Quieres que retomemos tu siguiente fase o control?", "variables": []},
            {"template_key": "recall_cleaning", "title": "Recall limpieza", "content": "Ya toca tu siguiente limpieza y control. Si quieres, te comparto horarios disponibles.", "variables": []},
            {"template_key": "deposit_request", "title": "Solicitud de anticipo", "content": "Para asegurar tu cita o fase de tratamiento, puedo enviarte el link de anticipo ahora mismo.", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["agendar", "calificar", "reactivar"],
            "policies": ["No emitir diagnosticos definitivos por chat", "Escalar urgencias dentales y contraindicaciones"],
            "can_say": ["valoracion", "especialista", "rango orientativo", "financiamiento", "agendar"],
            "cannot_say": ["diagnostico definitivo", "promesas clinicas absolutas", "medicacion"],
            "whatsapp_flows": ["triage_dental", "agenda_valoracion", "seguimiento_tratamiento", "recall_limpieza"],
            "appointment_duration_minutes": 40,
            "handoff_keywords": ["urgencia", "sangrado", "dolor", "infeccion"],
            "high_score_threshold": 85,
        },
    },
    {
        "id": "aesthetic",
        "name": "WAOS Aesthetic",
        "short_name": "Medicina estetica & wellness premium",
        "description": "Convierte curiosidad en pacientes de alto valor y recompra.",
        "problem": "El negocio depende de explicar bien, filtrar elegibilidad, vender paquetes y sostener mantenimiento, pero el seguimiento manual suele romper la conversion.",
        "subverticals": ["medicina estetica", "med spa", "faciales avanzados", "depilacion laser", "contouring corporal", "skin clinics", "anti-aging", "wellness premium", "aparatologia estetica", "rejuvenecimiento"],
        "objects": ["valoracion", "elegibilidad", "paquete", "sesion", "aftercare", "mantenimiento"],
        "flows": ["interes -> valoracion", "valoracion -> paquete", "sesion -> aftercare", "mantenimiento -> recompra"],
        "kpis": ["booking a valoracion", "aceptacion de paquete", "recompra", "mantenimiento activo"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "crm", "media"],
        "default_services": ["valoracion estetica", "facial avanzado", "depilacion laser", "paquete de sesiones", "mantenimiento mensual"],
        "default_faqs": [
            {"q": "¿Que tratamiento me conviene?", "a": "Podemos orientarte segun objetivo y agendar valoracion para definir elegibilidad."},
            {"q": "¿Cuantas sesiones se necesitan?", "a": "Depende del caso; el bot puede explicarte el flujo general y ayudarte a reservar valoracion."},
            {"q": "¿Tienen paquetes?", "a": "Si, podemos sugerir paquetes y mantenimiento cuando encajan contigo."},
            {"q": "¿Dan cuidados posteriores?", "a": "Si, enviamos instrucciones previas y aftercare despues de cada sesion."},
        ],
        "behavior": {
            "tone": "premium y consultivo",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "alta",
            "offer_promotions_when": "after_interest_confirmed",
            "escalate_when": ["contraindicacion", "reaccion adversa", "inconformidad"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": False,
            "auto_send_images": True,
            "bot_mode": "consultivo_premium",
            "active_channels": ["whatsapp", "instagram_dm", "webchat"],
            "forbidden_topics": ["promesas medicas absolutas", "diagnostico clinico definitivo"],
            "required_phrases": ["primero validamos elegibilidad", "puedo ayudarte a reservar tu valoracion"],
            "fallback_message": "Te ayudo a identificar el tratamiento o paquete que mejor encaja contigo y a reservar tu valoracion.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 90, "max_attempts": 2, "message_template": "¿Quieres que te recomiende el tratamiento adecuado o que apartemos tu valoracion?"},
            {"type": "post_quote", "delay_minutes": 1440, "max_attempts": 2, "message_template": "Sigo pendiente para ayudarte a elegir tu paquete o resolver dudas antes de reservar."},
            {"type": "reactivation", "delay_minutes": 20160, "max_attempts": 1, "message_template": "Ya toca mantenimiento o siguiente sesion. ¿Quieres que te comparta horarios disponibles?"},
        ],
        "templates": [
            {"template_key": "valuation_premium", "title": "Valoracion premium", "content": "Gracias por escribir a {{business_name}}. Te ayudo a revisar objetivo, elegibilidad y la mejor opcion para tu valoracion.", "variables": ["business_name"]},
            {"template_key": "package_offer", "title": "Oferta de paquete", "content": "Con base en tu objetivo, el paquete {{package_name}} suele dar mejor seguimiento que una sola sesion. ¿Quieres que te comparta detalles?", "variables": ["package_name"]},
            {"template_key": "precare", "title": "Instrucciones previas", "content": "Antes de tu cita, te comparto estas recomendaciones previas para que llegues lista/o al tratamiento.", "variables": []},
            {"template_key": "aftercare", "title": "Aftercare", "content": "Te comparto los cuidados posteriores recomendados para tu tratamiento de hoy. Si notas algo fuera de lo esperado, te canalizo con el especialista.", "variables": []},
            {"template_key": "maintenance", "title": "Mantenimiento", "content": "Tu mantenimiento recomendado ya esta cerca. ¿Quieres que te comparta horarios o el paquete vigente?", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["agendar", "upsell", "reactivar"],
            "policies": ["No prometer resultados garantizados", "Escalar contraindicaciones y reacciones"],
            "can_say": ["tratamientos", "sesiones", "paquetes", "aftercare", "mantenimiento"],
            "cannot_say": ["diagnostico definitivo", "promesas clinicas", "indicaciones medicas complejas"],
            "whatsapp_flows": ["valoracion_estetica", "venta_paquete", "aftercare", "mantenimiento"],
            "appointment_duration_minutes": 35,
            "handoff_keywords": ["contraindicacion", "alergia", "reaccion", "queja"],
            "high_score_threshold": 82,
        },
    },
    {
        "id": "vet",
        "name": "WAOS Vet",
        "short_name": "Veterinaria & pet care",
        "description": "Unifica consultas clinicas y servicios recurrentes alrededor de la mascota.",
        "problem": "Se pierden continuidad y recompra porque vacunas, consultas, grooming y seguimientos viven en conversaciones separadas y sin historial claro.",
        "subverticals": ["clinica veterinaria", "hospital veterinario", "vacunacion", "grooming", "hotel para mascotas", "daycare", "rehabilitacion", "nutricion veterinaria", "urgencias basicas", "planes preventivos"],
        "objects": ["mascota", "tutor", "vacunas", "plan preventivo", "historial", "proxima fecha clave"],
        "flows": ["registro mascota", "consulta o servicio", "post visita", "plan preventivo -> renovacion"],
        "kpis": ["vacunas al dia", "recompra grooming", "recompra plan preventivo", "no-show"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "crm"],
        "default_services": ["consulta general", "vacunacion", "grooming", "daycare", "plan preventivo"],
        "default_faqs": [
            {"q": "¿Pueden registrar a mi mascota?", "a": "Si, podemos registrar mascota, especie, raza y datos del tutor para dar mejor seguimiento."},
            {"q": "¿Manejan vacunas y recordatorios?", "a": "Si, enviamos recordatorios de vacunas, controles y servicios recurrentes."},
            {"q": "¿Puedo agendar grooming o consulta?", "a": "Si, el bot clasifica el motivo y te ayuda a reservar servicio o consulta."},
            {"q": "¿Tienen planes preventivos?", "a": "Si, podemos explicarte opciones y ayudarte a renovarlas."},
        ],
        "behavior": {
            "tone": "cercano y responsable",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "media",
            "offer_promotions_when": "after_pet_profile_completed",
            "escalate_when": ["urgencia", "accidente", "vomito continuo", "dificultad respiratoria"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": False,
            "auto_send_images": False,
            "bot_mode": "seguimiento_de_cuidado",
            "active_channels": ["whatsapp", "webchat"],
            "forbidden_topics": ["diagnostico veterinario definitivo por chat"],
            "required_phrases": ["te ayudo a registrar a tu mascota", "si es urgencia te canalizo con prioridad"],
            "fallback_message": "Te ayudo con consulta, grooming, vacunas o plan preventivo para tu mascota.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 120, "max_attempts": 2, "message_template": "¿Quieres que agendemos consulta, grooming o revisemos la siguiente vacuna?"},
            {"type": "post_quote", "delay_minutes": 1440, "max_attempts": 1, "message_template": "Quedo pendiente para ayudarte con la siguiente visita o plan preventivo de tu mascota."},
            {"type": "reactivation", "delay_minutes": 43200, "max_attempts": 1, "message_template": "Vemos que tu mascota ya podria requerir su siguiente servicio o control. ¿Quieres que te comparta horarios?"},
        ],
        "templates": [
            {"template_key": "pet_registration", "title": "Registro mascota", "content": "Para ayudarte mejor, comparteme nombre de tu mascota, especie, raza y el motivo de consulta o servicio.", "variables": []},
            {"template_key": "vaccine_reminder", "title": "Recordatorio de vacuna", "content": "Tu mascota ya esta cerca de su siguiente vacuna o control. ¿Quieres que lo agendemos?", "variables": []},
            {"template_key": "grooming_rebook", "title": "Rebook grooming", "content": "Ya toca el siguiente grooming recomendado. Si quieres, te comparto horarios disponibles.", "variables": []},
            {"template_key": "post_visit", "title": "Seguimiento post visita", "content": "¿Como siguio tu mascota despues de la visita? Si notas algo fuera de lo normal, te canalizo con el equipo.", "variables": []},
            {"template_key": "plan_renewal", "title": "Renovacion plan", "content": "Tu plan preventivo esta por vencer. ¿Quieres que te ayude a renovarlo hoy?", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["agendar", "reactivar", "renovar"],
            "policies": ["No emitir diagnosticos definitivos por chat", "Escalar urgencias veterinarias"],
            "can_say": ["consulta", "vacunas", "grooming", "planes preventivos", "agendar"],
            "cannot_say": ["diagnostico definitivo", "promesas clinicas absolutas"],
            "whatsapp_flows": ["registro_mascota", "agenda_vacuna", "grooming_rebook", "renovacion_plan"],
            "appointment_duration_minutes": 30,
            "handoff_keywords": ["urgencia", "respira mal", "accidente", "convulsiona"],
            "high_score_threshold": 88,
        },
    },
    {
        "id": "real-estate",
        "name": "WAOS Real Estate",
        "short_name": "Inmobiliaria & property lifecycle",
        "description": "Califica leads, agenda visitas y acompaña hasta cierre o renovacion.",
        "problem": "Entran muchos leads pero pocos estan bien calificados; sin filtro ni seguimiento, el asesor pierde tiempo y el negocio pierde cierres.",
        "subverticals": ["venta residencial", "renta residencial", "desarrollos", "preventa", "lujo", "brokers hipotecarios", "property management", "administracion de rentas", "comercial", "vacacional"],
        "objects": ["propiedad", "desarrollo", "presupuesto", "zona", "visita", "documentos"],
        "flows": ["lead -> perfilado", "perfilado -> visita", "visita -> seguimiento", "documentacion -> cierre"],
        "kpis": ["lead calificado", "visita agendada", "conversion por asesor", "cierres", "renovacion"],
        "recommended_integrations": ["whatsapp", "calendar", "crm", "webhooks"],
        "default_services": ["asesoria de compra", "visita guiada", "renta asistida", "precalificacion hipotecaria", "property management"],
        "default_faqs": [
            {"q": "¿Como me ayudan a encontrar propiedad?", "a": "Podemos perfilar presupuesto, zona e intencion para sugerirte opciones relevantes."},
            {"q": "¿Puedo agendar visita?", "a": "Si, el bot puede proponerte visita o llamada con el asesor correcto."},
            {"q": "¿Que documentos necesito?", "a": "Podemos orientarte sobre documentacion basica segun compra, renta o propiedad administrada."},
            {"q": "¿Tambien gestionan rentas?", "a": "Si, si operas property management podemos llevar renovaciones e incidencias basicas."},
        ],
        "behavior": {
            "tone": "consultivo y ejecutivo",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "alta",
            "offer_promotions_when": "after_budget_detected",
            "escalate_when": ["queja legal", "incidencia de inmueble", "oferta formal"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": True,
            "auto_send_images": True,
            "bot_mode": "calificacion_y_cierre",
            "active_channels": ["whatsapp", "webchat"],
            "forbidden_topics": ["asesoria legal definitiva", "promesas de aprobacion hipotecaria"],
            "required_phrases": ["te ayudo a perfilar tu busqueda", "puedo coordinar llamada o visita"],
            "fallback_message": "Te ayudo a filtrar propiedades, agendar visita y avanzar con el asesor correcto.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 180, "max_attempts": 2, "message_template": "¿Quieres que te comparta opciones segun tu presupuesto o prefieres agendar llamada con asesor?"},
            {"type": "post_quote", "delay_minutes": 1440, "max_attempts": 2, "message_template": "Sigo pendiente por si quieres retomar visita, propuesta o documentacion para avanzar."},
            {"type": "reactivation", "delay_minutes": 20160, "max_attempts": 1, "message_template": "Tengo nuevas opciones o disponibilidad para visita. ¿Quieres que retomemos tu busqueda?"},
        ],
        "templates": [
            {"template_key": "lead_profile", "title": "Perfilado de lead", "content": "Para recomendarte mejor, dime presupuesto, zona, compra o renta y cuando quieres mudarte o invertir.", "variables": []},
            {"template_key": "visit_booking", "title": "Agendar visita", "content": "Puedo coordinar tu visita a {{property_name}}. ¿Te funciona {{date_option_1}} o {{date_option_2}}?", "variables": ["property_name", "date_option_1", "date_option_2"]},
            {"template_key": "post_visit", "title": "Seguimiento post visita", "content": "¿Como te sentiste con la propiedad? Si quieres, avanzamos con propuesta, dudas o nuevas opciones.", "variables": []},
            {"template_key": "document_collection", "title": "Solicitud de documentos", "content": "Para avanzar, te comparto la lista inicial de documentos segun tu tipo de operacion.", "variables": []},
            {"template_key": "cold_lead_reactivation", "title": "Reactivacion lead frio", "content": "Retomo tu busqueda para compartirte opciones actualizadas segun tu presupuesto y zona ideal.", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["calificar", "agendar", "reactivar"],
            "policies": ["No prometer aprobacion financiera", "Escalar temas legales o disputas"],
            "can_say": ["propiedades", "rentas", "visitas", "documentos", "asesor asignado"],
            "cannot_say": ["promesas legales", "garantia de credito", "cierre asegurado"],
            "whatsapp_flows": ["perfilado_inmobiliario", "agenda_visita", "seguimiento_post_visita", "documentacion_basica"],
            "appointment_duration_minutes": 45,
            "handoff_keywords": ["oferta formal", "contrato", "queja", "incidencia"],
            "high_score_threshold": 78,
        },
    },
    {
        "id": "auto-service",
        "name": "WAOS Auto Service",
        "short_name": "Automotriz service & aftermarket",
        "description": "Profesionaliza intake, cotizacion, aprobacion y seguimiento del vehiculo.",
        "problem": "La friccion aparece por intake desordenado, cotizacion tardia, poca trazabilidad y mala comunicacion del avance del trabajo.",
        "subverticals": ["taller mecanico", "centro de servicio", "detailing", "PPF", "wraps", "hojalateria y pintura", "llantera", "servicio electrico automotriz", "accesorios", "lavado premium"],
        "objects": ["vehiculo", "VIN o placa", "diagnostico", "cotizacion", "aprobacion", "entrega"],
        "flows": ["solicitud -> intake", "revision -> cotizacion", "aprobacion -> trabajo", "entrega -> siguiente servicio"],
        "kpis": ["aprobacion de cotizacion", "tiempo de respuesta", "tiempo a entrega", "reingreso a mantenimiento"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "webhooks"],
        "default_services": ["revision inicial", "mantenimiento", "diagnostico electrico", "detailing", "llantas y frenos"],
        "default_faqs": [
            {"q": "¿Que datos del vehiculo necesitan?", "a": "El bot puede capturar placa o VIN, modelo, kilometraje y descripcion del problema."},
            {"q": "¿Pueden cotizar por WhatsApp?", "a": "Si, podemos iniciar una cotizacion preliminar y luego pedir aprobacion del cliente."},
            {"q": "¿Me avisan el avance?", "a": "Si, el bot puede comunicar estatus, refacciones y entrega."},
            {"q": "¿Recuerdan el siguiente servicio?", "a": "Si, configuramos recordatorios segun mantenimiento recomendado."},
        ],
        "behavior": {
            "tone": "tecnico y claro",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "media",
            "offer_promotions_when": "after_problem_classified",
            "escalate_when": ["seguro", "choque", "queja fuerte", "riesgo mecanico"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": True,
            "auto_send_images": True,
            "bot_mode": "intake_y_estatus",
            "active_channels": ["whatsapp", "webchat"],
            "forbidden_topics": ["garantias no autorizadas", "diagnosticos definitivos sin revision"],
            "required_phrases": ["te ayudo a registrar tu vehiculo", "si quieres iniciamos revision o cotizacion preliminar"],
            "fallback_message": "Te ayudo a registrar tu vehiculo, clasificar el problema y avanzar con revision o servicio.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 120, "max_attempts": 2, "message_template": "¿Quieres que retomemos tu revision, cotizacion o siguiente servicio del vehiculo?"},
            {"type": "post_quote", "delay_minutes": 1440, "max_attempts": 2, "message_template": "Quedo atento por si quieres aprobar la cotizacion o revisar alguna partida antes de avanzar."},
            {"type": "reactivation", "delay_minutes": 43200, "max_attempts": 1, "message_template": "Segun tu historial, ya podria tocar el siguiente mantenimiento. ¿Quieres que te comparta opciones?"},
        ],
        "templates": [
            {"template_key": "vehicle_intake", "title": "Intake vehicular", "content": "Comparteme placa o VIN, modelo, kilometraje y el problema que notas para orientarte mejor.", "variables": []},
            {"template_key": "diagnostic_booking", "title": "Agendar revision", "content": "Podemos agendar ingreso o revision diagnostica para {{date}}. ¿Te funciona?", "variables": ["date"]},
            {"template_key": "quote_approval", "title": "Solicitud de aprobacion", "content": "Ya tenemos la cotizacion inicial. Si te parece, te comparto detalle y avanzamos con tu aprobacion.", "variables": []},
            {"template_key": "status_update", "title": "Actualizacion de estatus", "content": "Tu vehiculo esta en etapa de {{job_status}}. Si surge alguna refaccion o cambio, te avisamos de inmediato.", "variables": ["job_status"]},
            {"template_key": "next_service", "title": "Siguiente servicio", "content": "Tu siguiente servicio recomendado se acerca. ¿Quieres que te proponga fecha de ingreso?", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["calificar", "agendar", "reactivar"],
            "policies": ["No prometer diagnosticos definitivos sin revision", "Escalar riesgos mecanicos y reclamos"],
            "can_say": ["revision", "cotizacion", "estatus", "entrega", "mantenimiento"],
            "cannot_say": ["garantias no autorizadas", "diagnostico final sin inspeccion"],
            "whatsapp_flows": ["intake_vehicular", "agenda_revision", "aprobacion_cotizacion", "recordatorio_mantenimiento"],
            "appointment_duration_minutes": 30,
            "handoff_keywords": ["seguro", "choque", "grua", "garantia"],
            "high_score_threshold": 80,
        },
    },
    {
        "id": "education",
        "name": "WAOS Education",
        "short_name": "Educacion & formacion",
        "description": "Automatiza admision, documentos, pagos e inscripcion.",
        "problem": "Se pierden prospectos entre preguntas repetidas, seguimiento incompleto y documentos pendientes antes de la inscripcion.",
        "subverticals": ["colegios privados", "universidades privadas", "idiomas", "academias", "tutorias", "bootcamps", "after school", "formacion tecnica", "educacion ejecutiva", "educacion continua"],
        "objects": ["programa", "nivel", "ciclo", "entrevista", "documentos", "inscripcion"],
        "flows": ["prospecto -> perfilado", "tour o entrevista", "documentos -> inscripcion", "renovacion de ciclo"],
        "kpis": ["lead a entrevista", "documentos completos", "inscripciones", "renovacion"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "crm"],
        "default_services": ["asesoria de admision", "tour o entrevista", "inscripcion", "programa intensivo", "renovacion de ciclo"],
        "default_faqs": [
            {"q": "¿Que programa me conviene?", "a": "Podemos orientar segun edad, nivel e interes para recomendar el programa adecuado."},
            {"q": "¿Puedo agendar tour o entrevista?", "a": "Si, el bot puede coordinar llamada, tour, entrevista o examen."},
            {"q": "¿Que documentos necesito?", "a": "Podemos perseguir documentos pendientes y explicarte el proceso de admision."},
            {"q": "¿Puedo pagar inscripcion?", "a": "Si, podemos enviarte enlace de pago o seguimiento de colegiatura si esta configurado."},
        ],
        "behavior": {
            "tone": "claro y orientador",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "media",
            "offer_promotions_when": "after_program_fit_detected",
            "escalate_when": ["beca especial", "caso academico sensible", "queja"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": True,
            "auto_send_images": True,
            "bot_mode": "admision_y_renovacion",
            "active_channels": ["whatsapp", "webchat"],
            "forbidden_topics": ["promesas de admision garantizada"],
            "required_phrases": ["te ayudo a identificar el programa correcto", "puedo guiarte en el proceso de admision"],
            "fallback_message": "Te ayudo a encontrar programa, revisar requisitos y avanzar hasta inscripcion.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 180, "max_attempts": 2, "message_template": "¿Quieres que te recomiende programa o agendemos llamada, tour o entrevista?"},
            {"type": "post_quote", "delay_minutes": 1440, "max_attempts": 2, "message_template": "Sigo pendiente por si quieres retomar admision, documentos o pago de inscripcion."},
            {"type": "reactivation", "delay_minutes": 43200, "max_attempts": 1, "message_template": "Todavia podemos ayudarte a completar tu proceso o renovar tu siguiente ciclo. ¿Lo retomamos?"},
        ],
        "templates": [
            {"template_key": "admissions_intake", "title": "Intake admision", "content": "Para orientarte mejor, dime edad o nivel del alumno, programa de interes y campus preferido.", "variables": []},
            {"template_key": "tour_booking", "title": "Agendar tour", "content": "Puedo apartarte un tour o entrevista para {{date}}. ¿Te funciona ese horario?", "variables": ["date"]},
            {"template_key": "documents_followup", "title": "Seguimiento documentos", "content": "Te comparto los documentos pendientes para avanzar con tu inscripcion. Si quieres, los revisamos juntos.", "variables": []},
            {"template_key": "enrollment_payment", "title": "Pago de inscripcion", "content": "Si quieres asegurar tu lugar, te envio el link de pago de inscripcion ahora mismo.", "variables": []},
            {"template_key": "renewal_cycle", "title": "Renovacion de ciclo", "content": "Tu siguiente ciclo o nivel ya esta cerca. ¿Quieres que te ayude a renovarlo?", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["calificar", "agendar", "renovar"],
            "policies": ["No garantizar admision sin proceso", "Escalar casos sensibles o becas especiales"],
            "can_say": ["programas", "campus", "entrevistas", "documentos", "inscripcion", "colegiatura"],
            "cannot_say": ["admision garantizada", "beca aprobada sin validacion"],
            "whatsapp_flows": ["perfilado_programa", "tour_entrevista", "seguimiento_documentos", "renovacion_ciclo"],
            "appointment_duration_minutes": 30,
            "handoff_keywords": ["beca", "queja", "caso academico", "reembolso"],
            "high_score_threshold": 76,
        },
    },
    {
        "id": "beauty",
        "name": "WAOS Beauty",
        "short_name": "Belleza personal & self-care",
        "description": "Reduce no-shows, mejora ocupacion y ordena la recompra por agenda.",
        "problem": "La operacion se llena de mensajes repetitivos, huecos de agenda y poca reactivacion estructurada.",
        "subverticals": ["salon", "barberia", "unas", "lashes", "brows", "maquillaje", "peinado social", "bridal beauty", "skincare studio", "hair color"],
        "objects": ["servicio", "especialista", "duracion", "cabina o silla", "anticipo", "rebook"],
        "flows": ["descubrimiento -> disponibilidad", "anticipo -> confirmacion", "cita -> add-on", "rebook -> recompra"],
        "kpis": ["ocupacion", "no-show", "rebook rate", "ticket promedio"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "media"],
        "default_services": ["corte", "color", "unas", "lashes", "facial"],
        "default_faqs": [
            {"q": "¿Que servicio me recomiendan?", "a": "Podemos orientarte segun resultado deseado y tiempo disponible."},
            {"q": "¿Como veo horarios?", "a": "Si, podemos mostrar disponibilidad por servicio o especialista."},
            {"q": "¿Piden anticipo?", "a": "Si, si tu negocio lo requiere, el bot puede cobrar anticipo y confirmar cita."},
            {"q": "¿Puedo reagendar?", "a": "Si, podemos aplicar politica de cancelacion o rebook segun tus reglas."},
        ],
        "behavior": {
            "tone": "cercano y aspiracional",
            "response_length": "corta",
            "use_emojis": False,
            "sales_intensity": "alta",
            "offer_promotions_when": "after_service_interest_detected",
            "escalate_when": ["queja de servicio", "tema sensible de imagen"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": False,
            "auto_send_images": True,
            "bot_mode": "agenda_y_rebook",
            "active_channels": ["whatsapp", "instagram_dm"],
            "forbidden_topics": ["promesas esteticas absolutas"],
            "required_phrases": ["te ayudo a elegir servicio y horario", "puedo reservar con tu especialista ideal"],
            "fallback_message": "Te ayudo a elegir servicio, ver disponibilidad y dejar confirmada tu cita.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 60, "max_attempts": 2, "message_template": "¿Quieres que te comparta horarios o te recomiende el servicio ideal?"},
            {"type": "post_quote", "delay_minutes": 720, "max_attempts": 2, "message_template": "Todavia puedo ayudarte a reservar tu cita o a elegir add-ons para tu servicio."},
            {"type": "reactivation", "delay_minutes": 20160, "max_attempts": 1, "message_template": "Ya podria tocar tu siguiente cita ideal. ¿Quieres que te comparta disponibilidad?"},
        ],
        "templates": [
            {"template_key": "service_match", "title": "Recomendacion de servicio", "content": "Cuentame que resultado buscas y te recomiendo servicio, especialista y tiempo estimado.", "variables": []},
            {"template_key": "appointment_hold", "title": "Apartado de cita", "content": "Tengo espacio para {{service_name}} el {{date}} a las {{time}}. ¿Quieres que lo deje apartado?", "variables": ["service_name", "date", "time"]},
            {"template_key": "deposit", "title": "Cobro de anticipo", "content": "Para confirmar tu cita, te comparto el link de anticipo ahora mismo.", "variables": []},
            {"template_key": "rebook", "title": "Rebook sugerido", "content": "Para mantener tu resultado ideal, te sugiero reservar tu siguiente cita desde ahora. ¿Quieres que te muestre horarios?", "variables": []},
            {"template_key": "inactive_client", "title": "Cliente inactivo", "content": "Hace tiempo que no te vemos. Si quieres, te recomiendo servicio ideal y disponibilidad actual.", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["agendar", "upsell", "reactivar"],
            "policies": ["No prometer resultados absolutos", "Escalar reclamos o casos sensibles"],
            "can_say": ["servicios", "especialista", "duracion", "anticipo", "rebook"],
            "cannot_say": ["garantias absolutas de resultado"],
            "whatsapp_flows": ["recomendacion_servicio", "anticipo_cita", "rebook_sugerido", "reactivacion_cliente"],
            "appointment_duration_minutes": 60,
            "handoff_keywords": ["queja", "alergia", "inconformidad"],
            "high_score_threshold": 72,
        },
    },
    {
        "id": "field-services",
        "name": "WAOS Field Services",
        "short_name": "Home services & field services",
        "description": "Convierte la conversacion inicial en una orden de trabajo despachable.",
        "problem": "Se pierde tiempo en urgencias mal priorizadas, visitas sin contexto y chats sin datos suficientes para asignar tecnico.",
        "subverticals": ["HVAC", "plomeria", "electricidad", "cerrajeria", "paneles solares", "limpieza especializada", "fumigacion", "jardineria", "mantenimiento residencial", "seguridad electronica"],
        "objects": ["incidente", "prioridad", "ubicacion", "tecnico", "orden de trabajo", "garantia"],
        "flows": ["problema -> triage", "triage -> tecnico", "visita -> cobro", "cierre -> garantia"],
        "kpis": ["tiempo a despacho", "first visit fix", "cobro", "reclamos en garantia"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "webhooks"],
        "default_services": ["visita diagnostica", "reparacion urgente", "mantenimiento preventivo", "servicio en sitio", "garantia"],
        "default_faqs": [
            {"q": "¿Pueden atender urgencias?", "a": "Si, el bot clasifica prioridad y recopila lo necesario para asignar tecnico o visita."},
            {"q": "¿Piden fotos o ubicacion?", "a": "Si, podemos solicitar evidencia y direccion para despachar mejor."},
            {"q": "¿Dan rango de precio?", "a": "Podemos estimar un servicio inicial o programar visita diagnostica."},
            {"q": "¿Manejan garantia?", "a": "Si, podemos dejar seguimiento o garantia posterior si aplica."},
        ],
        "behavior": {
            "tone": "directo y resolutivo",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "media",
            "offer_promotions_when": "after_issue_categorized",
            "escalate_when": ["riesgo electrico", "fuga grave", "seguridad", "emergencia"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": True,
            "auto_send_images": False,
            "bot_mode": "triage_y_despacho",
            "active_channels": ["whatsapp", "webchat"],
            "forbidden_topics": ["garantia total sin diagnostico"],
            "required_phrases": ["te ayudo a clasificar la urgencia", "puedo coordinar visita o tecnico"],
            "fallback_message": "Te ayudo a clasificar el problema, tomar datos clave y coordinar la visita correcta.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 45, "max_attempts": 2, "message_template": "¿Quieres que retomemos tu servicio y coordinemos tecnico o visita?"},
            {"type": "post_quote", "delay_minutes": 720, "max_attempts": 2, "message_template": "Sigo pendiente por si quieres avanzar con la visita o aceptar el servicio propuesto."},
            {"type": "reactivation", "delay_minutes": 43200, "max_attempts": 1, "message_template": "Si quieres, te ayudo a programar mantenimiento preventivo o revisar garantia de servicio."},
        ],
        "templates": [
            {"template_key": "incident_triage", "title": "Triage de incidente", "content": "Cuentame que sucede, si es urgente y comparteme ubicacion o foto para asignar mejor la visita.", "variables": []},
            {"template_key": "dispatch_visit", "title": "Despacho de visita", "content": "Puedo coordinar una visita para {{date}} en tu zona. ¿Te funciona?", "variables": ["date"]},
            {"template_key": "estimate", "title": "Estimacion inicial", "content": "Con lo que nos compartes, podemos darte una estimacion inicial o agendar visita diagnostica.", "variables": []},
            {"template_key": "status_field", "title": "Estatus de servicio", "content": "Tu orden esta en {{status}}. Si hay ajuste o llegada estimada, te lo comparto por aqui.", "variables": ["status"]},
            {"template_key": "warranty_followup", "title": "Seguimiento garantia", "content": "Te escribimos para confirmar que todo quedo bien y ayudarte con cualquier garantia o ajuste.", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["calificar", "agendar", "cobrar"],
            "policies": ["Escalar riesgos de seguridad o emergencias", "No garantizar solucion final sin visita"],
            "can_say": ["urgencia", "tecnico", "visita", "estimacion", "garantia"],
            "cannot_say": ["diagnostico final sin visita", "garantia total sin validacion"],
            "whatsapp_flows": ["triage_servicio", "agenda_visita_tecnica", "estimacion_inicial", "seguimiento_garantia"],
            "appointment_duration_minutes": 60,
            "handoff_keywords": ["emergencia", "riesgo", "seguridad", "seguro"],
            "high_score_threshold": 90,
        },
    },
    {
        "id": "professional-intake",
        "name": "WAOS Professional Intake",
        "short_name": "Servicios profesionales de alto seguimiento",
        "description": "Protege tiempo experto con intake, elegibilidad y seguimiento bien estructurados.",
        "problem": "Muchos equipos desperdician horas en leads mal calificados, intake incompleto y documentacion mal gestionada.",
        "subverticals": ["legal", "migracion", "contabilidad", "fiscal", "seguros", "consultoria especializada", "gestoria", "notarial", "compliance", "brokers financieros"],
        "objects": ["tipo de caso", "especialidad", "consulta", "fee", "documentos", "milestone"],
        "flows": ["intake -> elegibilidad", "consulta -> anticipo", "expediente -> seguimiento", "renovacion -> continuidad"],
        "kpis": ["lead calificado", "show rate a consulta", "fee cobrado", "renovacion"],
        "recommended_integrations": ["whatsapp", "calendar", "payments", "crm"],
        "default_services": ["consulta inicial", "revision de caso", "expediente", "seguimiento", "renovacion o continuidad"],
        "default_faqs": [
            {"q": "¿Como clasifican mi caso?", "a": "El bot hace intake inicial y puede dirigirte con la especialidad correcta."},
            {"q": "¿Pueden pedir documentos?", "a": "Si, podemos solicitar documentos iniciales para preparar la consulta o expediente."},
            {"q": "¿La consulta se paga?", "a": "Si, si tu operacion lo requiere, podemos cobrar consulta o anticipo desde el chat."},
            {"q": "¿Dan seguimiento a vencimientos?", "a": "Si, el bot puede recordar milestones, renovaciones o vencimientos importantes."},
        ],
        "behavior": {
            "tone": "serio y profesional",
            "response_length": "media",
            "use_emojis": False,
            "sales_intensity": "media",
            "offer_promotions_when": "never",
            "escalate_when": ["urgencia legal", "riesgo regulatorio", "caso sensible"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": False,
            "auto_send_images": False,
            "bot_mode": "intake_profesional",
            "active_channels": ["whatsapp", "webchat"],
            "forbidden_topics": ["asesoria definitiva por chat", "promesas de resultado"],
            "required_phrases": ["te ayudo a clasificar tu caso", "si quieres, agendamos consulta con el especialista correcto"],
            "fallback_message": "Te ayudo a ordenar tu caso, pedir lo necesario y llevarte con el especialista correcto.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 240, "max_attempts": 2, "message_template": "¿Quieres que retomemos tu caso y revisemos la consulta o documentacion inicial?"},
            {"type": "post_quote", "delay_minutes": 1440, "max_attempts": 2, "message_template": "Sigo atento por si quieres avanzar con consulta, fee o envio de documentos."},
            {"type": "reactivation", "delay_minutes": 43200, "max_attempts": 1, "message_template": "Te recordamos que tu expediente o renovacion sigue abierto. ¿Quieres retomarlo hoy?"},
        ],
        "templates": [
            {"template_key": "case_intake", "title": "Intake de caso", "content": "Para orientarte mejor, dime tipo de caso, urgencia, pais o jurisdiccion y objetivo principal.", "variables": []},
            {"template_key": "consult_booking", "title": "Agendar consulta", "content": "Puedo coordinar tu consulta con {{specialty}} para {{date}}. ¿Te funciona?", "variables": ["specialty", "date"]},
            {"template_key": "document_request", "title": "Solicitud de documentos", "content": "Antes de la consulta, te comparto la documentacion inicial sugerida para avanzar con tu caso.", "variables": []},
            {"template_key": "fee_collection", "title": "Cobro de consulta", "content": "Si quieres asegurar tu espacio o abrir expediente, te envio el link de pago ahora mismo.", "variables": []},
            {"template_key": "renewal_due", "title": "Recordatorio de vencimiento", "content": "Tu siguiente vencimiento o renovacion se acerca. ¿Quieres que te ayudemos a continuarlo?", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["calificar", "agendar", "renovar"],
            "policies": ["No dar asesoria definitiva por chat", "Escalar casos sensibles o de alto riesgo"],
            "can_say": ["consulta", "especialidad", "fee", "documentos", "vencimientos"],
            "cannot_say": ["resultado garantizado", "asesoria definitiva", "promesas legales"],
            "whatsapp_flows": ["intake_caso", "agenda_consulta", "documentos_iniciales", "recordatorio_vencimiento"],
            "appointment_duration_minutes": 45,
            "handoff_keywords": ["urgencia", "demanda", "auditoria", "vencimiento inmediato"],
            "high_score_threshold": 92,
        },
    },
    {
        "id": "commerce",
        "name": "WAOS Commerce",
        "short_name": "Commerce & retail conversacional",
        "description": "Convierte conversaciones en pedidos, pagos, seguimiento y recompra.",
        "problem": "La gente pregunta por precio, talla, color, stock o envio y el negocio no convierte la conversacion en pedido ni recupera carritos abandonados.",
        "subverticals": ["ropa", "tenis", "joyeria", "gorras", "accesorios", "bolsas", "cosmetica y skincare", "regalos", "home decor", "gadgets", "merch", "drops de temporada"],
        "objects": ["catalogo", "variantes", "stock", "carrito conversacional", "link de pago", "envio"],
        "flows": ["descubrimiento -> recomendacion", "pregunta -> carrito", "pago -> confirmacion", "envio -> recompra"],
        "kpis": ["conversion por chat", "carrito recuperado", "ticket promedio", "recompra"],
        "recommended_integrations": ["whatsapp", "payments", "commerce", "media", "webhooks"],
        "default_services": ["descubrimiento de producto", "armado de pedido", "pago por link", "seguimiento de envio", "recompra y cross-sell"],
        "default_faqs": [
            {"q": "¿Tienen talla, color o stock?", "a": "Si, el bot puede responder variantes, precio y disponibilidad del catalogo conectado."},
            {"q": "¿Puedo comprar por WhatsApp?", "a": "Si, podemos ayudarte a armar pedido y enviarte link de pago."},
            {"q": "¿Que pasa si no termino la compra?", "a": "El bot puede retomar carritos conversacionales y ayudarte a cerrarlos."},
            {"q": "¿Me avisan del envio?", "a": "Si, podemos confirmar compra y compartir estatus de envio o entrega."},
        ],
        "behavior": {
            "tone": "vendedor digital",
            "response_length": "corta",
            "use_emojis": False,
            "sales_intensity": "alta",
            "offer_promotions_when": "always_when_relevant",
            "escalate_when": ["fraude", "reclamo fuerte", "devolucion compleja"],
            "insistence_policy": "respectful",
            "can_share_price_directly": True,
            "can_negotiate": False,
            "can_mention_stock": True,
            "auto_send_images": True,
            "bot_mode": "venta_conversacional",
            "active_channels": ["whatsapp", "instagram_dm", "webchat"],
            "forbidden_topics": ["inventario no validado", "promesas de entrega no configuradas"],
            "required_phrases": ["te ayudo a encontrar producto", "puedo armar tu pedido y enviarte link de pago"],
            "fallback_message": "Te ayudo a elegir producto, revisar variantes y cerrar tu compra por chat.",
        },
        "followup_rules": [
            {"type": "no_response", "delay_minutes": 45, "max_attempts": 2, "message_template": "¿Quieres que te comparta opciones, confirme stock o arme tu pedido?"},
            {"type": "post_quote", "delay_minutes": 360, "max_attempts": 2, "message_template": "Todavia puedo ayudarte a completar tu compra o resolver talla, color, stock y envio."},
            {"type": "reactivation", "delay_minutes": 10080, "max_attempts": 2, "message_template": "Tenemos novedades, reposiciones o complementos que pueden encajar contigo. ¿Quieres ver opciones?"},
        ],
        "templates": [
            {"template_key": "product_discovery", "title": "Descubrimiento de producto", "content": "Cuentame que buscas y te recomiendo opciones de catalogo con precio, color, talla o variante disponible.", "variables": []},
            {"template_key": "cart_build", "title": "Armado de carrito", "content": "Ya tengo tu pedido casi listo. Si quieres, confirmamos variante, envio y te mando el link de pago.", "variables": []},
            {"template_key": "payment_link", "title": "Link de pago", "content": "Perfecto. Te comparto el link de pago para confirmar tu compra en este momento.", "variables": []},
            {"template_key": "shipment_update", "title": "Estatus de envio", "content": "Tu pedido ya esta en etapa de {{shipping_status}}. Si quieres, te comparto el siguiente paso o referencia.", "variables": ["shipping_status"]},
            {"template_key": "abandoned_cart", "title": "Recuperacion carrito", "content": "Tu pedido sigue disponible. Si quieres, retomamos talla, color, stock o metodo de pago para cerrarlo hoy.", "variables": []},
        ],
        "config_overrides": {
            "objective_secondary": ["vender", "upsell", "reactivar"],
            "policies": ["No prometer stock o entregas no confirmadas", "Escalar fraudes o devoluciones sensibles"],
            "can_say": ["precio", "stock", "color", "talla", "envio", "promocion", "link de pago"],
            "cannot_say": ["stock no validado", "entregas no configuradas", "promesas logisticas"],
            "whatsapp_flows": ["descubrimiento_producto", "carrito_conversacional", "link_de_pago", "recuperacion_carrito"],
            "appointment_duration_minutes": 20,
            "handoff_keywords": ["fraude", "cobro duplicado", "devolucion", "reembolso"],
            "high_score_threshold": 70,
        },
    },
    {'id': 'waos-bot',
     'name': 'WAOS Bot',
     'short_name': 'Bot que vende WAOS',
     'description': 'Convierte conversaciones caoticas en diagnostico, confianza y demo.',
     'problem': 'Los prospectos preguntan de todo, se salen del tema, bromean, se frustran o llegan sin contexto. Si el '
                'bot se seca o suena tecnico, mata confianza y venta.',
     'subverticals': ['prospectos inbound',
                      'referidos',
                      'campanas',
                      'reactivacion de leads frios',
                      'agenda de demos',
                      'cierres consultivos',
                      'takeover humano',
                      'instalacion'],
     'objects': ['lead',
                 'dolor',
                 'fuga comercial',
                 'objecion',
                 'diagnostico',
                 'demo',
                 'takeover humano',
                 'seguimiento',
                 'propuesta',
                 'instalacion'],
     'flows': ['caos -> entendimiento',
               'duda -> reencuadre comercial',
               'interes -> diagnostico',
               'diagnostico -> demo',
               'demo -> propuesta',
               'propuesta -> instalacion',
               'lead frio -> reactivacion'],
     'kpis': ['reply speed',
              'lead to demo',
              'demo show rate',
              'demo to propuesta',
              'propuesta a cierre',
              'reactivacion de leads',
              'conversaciones que no mueren'],
     'recommended_integrations': ['whatsapp', 'crm', 'calendar', 'webhooks', 'analytics'],
     'default_services': ['diagnostico express', 'demo guiada', 'setup inicial', 'instalacion', 'takeover humano'],
     'default_faqs': [{'q': 'Que hace WAOS exactamente?',
                       'a': 'Te ayuda a responder mejor, seguir prospectos, no perder leads y mover conversaciones a venta '
                            'por WhatsApp.'},
                      {'q': 'Va a sonar como robot?',
                       'a': 'No deberia. Esta vertical esta pensada para sonar cercana, clara y comercial, sin verse tiesa '
                            'ni tecnica.'},
                      {'q': 'Puede aguantar preguntas raras o bromas?',
                       'a': 'Si. La idea es que nunca se quede seco: conecta, responde, reubica y sigue vendiendo.'},
                      {'q': 'Tambien agenda demos o seguimiento?',
                       'a': 'Si. Puede llevar a demo, diagnostico, propuesta o takeover humano segun el momento del '
                            'prospecto.'}],
     'behavior': {'tone': 'cercano, relajado y filoso',
                  'response_length': 'media',
                  'use_emojis': False,
                  'sales_intensity': 'alta',
                  'offer_promotions_when': 'after_pain_detected',
                  'escalate_when': ['pide humano',
                                    'caso tecnico profundo',
                                    'contrato',
                                    'precio enterprise',
                                    'queja fuerte'],
                  'insistence_policy': 'respectful',
                  'can_share_price_directly': False,
                  'can_negotiate': False,
                  'can_mention_stock': False,
                  'auto_send_images': False,
                  'bot_mode': 'diagnostico_y_cierre_consultivo',
                  'active_channels': ['whatsapp', 'webchat', 'instagram_dm'],
                  'forbidden_topics': ['inventar funciones',
                                       'prometer resultados exactos',
                                       'fingir ser persona',
                                       'hablar como sistema'],
                  'required_phrases': ['nunca se queda seco', 'te lo aterrizo a tu caso'],
                  'fallback_message': 'Te sigo. Aunque la conversacion venga medio en caos, te ayudo a aterrizar si hoy te '
                                      'conviene responder mejor, seguir leads o cerrar mas por WhatsApp.'},
     'followup_rules': [{'type': 'no_response',
                         'delay_minutes': 180,
                         'max_attempts': 2,
                         'message_template': 'Solo retomando esto porque por lo que me contaste si hay una fuga clara. Si '
                                             'quieres te lo aterrizo en 2 minutos a tu negocio.'},
                        {'type': 'post_quote',
                         'delay_minutes': 1440,
                         'max_attempts': 2,
                         'message_template': 'Quedo pendiente por si quieres ver un ejemplo ya aterrizado a tu caso o '
                                             'revisar como no dejar leads tirados en WhatsApp.'},
                        {'type': 'reactivation',
                         'delay_minutes': 10080,
                         'max_attempts': 1,
                         'message_template': 'Paso rapido por aqui porque esto sigue sonando a que traes ventas fugandose. '
                                             'Si quieres, vemos donde meter WAOS sin complicarte mas la operacion.'}],
     'templates': [{'template_key': 'lead_capture',
                    'title': 'Entrada con colmillo',
                    'content': 'Que bueno que escribiste. Te ayudo a aterrizar rapido si hoy el dolor esta en responder, '
                               'seguir prospectos o cerrar mejor por WhatsApp.',
                    'variables': []},
                   {'template_key': 'pain_diagnosis',
                    'title': 'Mini diagnostico',
                    'content': 'Por como lo cuentas, aqui no falta que contestes mas: falta que el seguimiento no se '
                               'enfrie. Si quieres te hago un mini diagnostico.',
                    'variables': []},
                   {'template_key': 'demo_offer',
                    'title': 'Invitacion a demo',
                    'content': 'Si te late, te enseño con un ejemplo como se veria WAOS contestando, reubicando y moviendo '
                               'la conversacion a venta en tu negocio.',
                    'variables': []},
                   {'template_key': 'objection_followup',
                    'title': 'Seguimiento con humor ligero',
                    'content': 'La neta, si esto siguiera cayendo en ti todo el dia cualquiera se quema. Por eso vale la '
                               'pena ver como lo bajamos con WAOS. ¿Lo aterrizamos?',
                    'variables': []},
                   {'template_key': 'human_takeover',
                    'title': 'Takeover humano',
                    'content': 'Aqui ya conviene que te pase con alguien del equipo para verlo fino y sin vueltas. Si '
                               'quieres te conecto.',
                    'variables': []}],
     'config_overrides': {'objective_secondary': ['diagnosticar', 'agendar', 'cerrar'],
                          'policies': ['No inventar funciones, precios ni politicas',
                                       'No fingir ser persona',
                                       'No cortar conversaciones en frio',
                                       'Primero validar el momento emocional y luego vender'],
                          'can_say': ['responder mejor',
                                      'seguir leads',
                                      'agendar demo',
                                      'takeover humano',
                                      'recuperar conversaciones frias',
                                      'ordenar WhatsApp'],
                          'cannot_say': ['jerga tecnica',
                                         'promesas de resultados exactos',
                                         'precios inventados',
                                         'frases roboticas'],
                          'whatsapp_flows': ['diagnostico_express',
                                             'agenda_demo',
                                             'seguimiento_objecion',
                                             'reactivacion_lead_frio',
                                             'takeover_humano'],
                          'appointment_duration_minutes': 30,
                          'handoff_keywords': ['humano',
                                               'asesor',
                                               'equipo',
                                               'contrato',
                                               'precio enterprise',
                                               'integracion especifica'],
                          'high_score_threshold': 78}}
]

_VERTICALS = _apply_portfolio_updates(_VERTICALS)

_VERTICAL_ALIASES = {
    "waos fitness": "fitness",
    "fitness & entrenamiento": "fitness",
    "fitness": "fitness",
    "clinicas dentales": "dental",
    "dental": "dental",
    "waos dental": "dental",
    "medicina estetica": "aesthetic",
    "medicina estetica & wellness premium": "aesthetic",
    "waos aesthetic": "aesthetic",
    "veterinaria": "vet",
    "veterinaria & pet care": "vet",
    "waos vet": "vet",
    "inmobiliaria": "real-estate",
    "inmobiliaria & property lifecycle": "real-estate",
    "waos real estate": "real-estate",
    "automotriz": "auto-service",
    "automotriz service & aftermarket": "auto-service",
    "waos auto service": "auto-service",
    "educacion": "education",
    "educacion & formacion": "education",
    "waos education": "education",
    "belleza": "beauty",
    "belleza personal & self-care": "beauty",
    "waos beauty": "beauty",
    "home services": "field-services",
    "home services & field services": "field-services",
    "field services": "field-services",
    "waos field services": "field-services",
    "servicios profesionales": "professional-intake",
    "servicios profesionales de alto seguimiento": "professional-intake",
    "waos professional intake": "professional-intake",
    "commerce": "commerce",
    "commerce & retail conversacional": "commerce",
    "retail conversacional": "commerce",
    "waos commerce": "commerce",
    "waos bot": "waos-bot",
    "bot de waos": "waos-bot",
    "vender waos": "waos-bot",
    "waos master": "waos-bot",
}

_VERTICALS_BY_ID = {item["id"]: item for item in _VERTICALS}
_DEFAULT_VERTICAL_ID = "commerce"


def normalize_vertical_key(value: str | None) -> str:
    if not value:
        return _DEFAULT_VERTICAL_ID
    normalized = str(value).strip().lower()
    if normalized in _VERTICALS_BY_ID:
        return normalized
    if normalized in _VERTICAL_ALIASES:
        return _VERTICAL_ALIASES[normalized]
    for item in _VERTICALS:
        if normalized == item["name"].lower() or normalized == item["short_name"].lower():
            return item["id"]
    return _DEFAULT_VERTICAL_ID


def get_vertical_profile(value: str | None) -> dict[str, Any]:
    return _apply_global_conversation_defaults(_VERTICALS_BY_ID[normalize_vertical_key(value)])


def list_vertical_profiles() -> list[dict[str, Any]]:
    return [get_vertical_profile(item["id"]) for item in _VERTICALS]


def _list_or_default(value: list[str] | list[dict[str, Any]] | None, fallback: list[Any]) -> list[Any]:
    return list(value) if value else deepcopy(fallback)


def build_vertical_bot_setup(
    value: str | None,
    *,
    business_name: str,
    bot_name: str,
    tone: str,
    language: str,
    timezone: str,
    primary_objective: str,
    services: list[str] | None = None,
    faqs: list[dict[str, Any]] | None = None,
    hours: str = "",
    whatsapp_number: str = "",
) -> dict[str, Any]:
    profile = get_vertical_profile(value)
    overrides = profile.get("config_overrides", {})
    availability = [hours] if hours else ["por configurar"]
    return {
        "profile": profile,
        "services": _list_or_default(services, profile.get("default_services", [])),
        "faqs": _list_or_default(faqs, profile.get("default_faqs", [])),
        "rules": {
            "can_say": _list_or_default(overrides.get("can_say"), ["servicios", "horarios", "precio si existe configurado", "agendar"]),
            "cannot_say": _list_or_default(overrides.get("cannot_say"), ["datos no configurados", "promesas contractuales", "diagnosticos profesionales"]),
            "escalate_when": _list_or_default(profile.get("behavior", {}).get("escalate_when"), ["cliente molesto", "pide humano", "tema sensible"]),
            "objection_handling": _list_or_default(profile.get("bot_playbook", {}).get("objections"), ["precio", "tiempo", "confianza", "siguiente paso"]),
            "must_ask": _list_or_default(profile.get("bot_playbook", {}).get("must_ask"), []),
            "success_signals": _list_or_default(profile.get("bot_playbook", {}).get("success_signals"), []),
            "do_not_reply_when": ["human_takeover", "paused", "blocked"],
            "followup_limits": {"max_attempts": 2, "quiet_hours": "21:00-08:00"},
        },
        "agenda": {
            "availability": availability,
            "appointment_duration_minutes": int(overrides.get("appointment_duration_minutes") or 30),
            "buffer_minutes": 15,
            "confirmation_rules": "confirmar 24h antes",
            "reschedule_rules": "permitir una reprogramacion",
        },
        "followups": {"rules": _list_or_default(profile.get("followup_rules"), [])},
        "handoff": {
            "sensitive_keywords": _list_or_default(overrides.get("handoff_keywords"), ["humano", "asesor", "agente", "reclamo", "queja", "molesto"]),
            "high_score_threshold": int(overrides.get("high_score_threshold") or 80),
            "strong_buy_signals": ["quiero comprar", "quiero agendar", "me interesa", "listo", "avancemos"],
            "angry_customer_keywords": ["molesto", "enojado", "queja", "pesimo", "mal servicio"],
        },
        "personality": {
            "formality": "semi-formal",
            "tone": tone or profile.get("behavior", {}).get("tone") or "amable",
            "response_length": profile.get("behavior", {}).get("response_length") or "short",
            "use_emojis": bool(profile.get("behavior", {}).get("use_emojis")),
            "sales_intensity": profile.get("behavior", {}).get("sales_intensity") or "medium",
            "tone_of_voice_understanding": True,
            "tone_adaptation": "mirror_lightly_keep_brand",
            "native_voice_by_language": True,
            "tone_matrix_by_language": True,
        },
        "objective": {
            "primary": primary_objective,
            "secondary": _list_or_default(overrides.get("objective_secondary"), ["responder_faq", "calificar", "reactivar"]),
        },
        "business_knowledge": {
            "hours": hours,
            "policies": _list_or_default(overrides.get("policies"), []),
            "location": "",
            "promotions": [],
            "products": [],
            "prices": [],
        },
        "integrations": {
            "whatsapp": {"provider": "meta_cloud_api", "phone_number": whatsapp_number},
            "calendar": {"mode": "google_oauth", "sync_strategy": "bidirectional"},
            "instagram_dm": {"enabled": "instagram_dm" in (profile.get("behavior", {}).get("active_channels") or [])},
            "webchat": {"enabled": "webchat" in (profile.get("behavior", {}).get("active_channels") or []) or not profile.get("behavior", {}).get("active_channels")},
            "webhooks": [],
        },
        "v7_modules": {
            "commerce": {
                "payments_in_chat": True,
                "auto_payment_reminders": True,
                "auto_payment_confirmation": True,
                "lead_close_on_payment": True,
                "receipt_via_whatsapp": True,
                "abandoned_quote_recovery": True,
            },
            "whatsapp_flows": _list_or_default(overrides.get("whatsapp_flows"), ["precalificacion", "agendar_cita", "cotizacion_guiada", "actualizacion_datos"]),
            "seller_mode": {
                "intent_scoring": True,
                "close_probability": True,
                "next_best_action": True,
                "objection_assist": True,
                "cooling_alert": True,
                "advisor_summary": True,
            },
            "multilingual": {
                "bot_language": language,
                "supported_languages": ["es", "en"],
                "detect_contact_language": True,
                "reply_in_detected_language": True,
                "template_languages": ["es", "en"],
                "fallback_by_language": True,
                "fallback_language": "en" if language == "es" else "es",
                "human_handoff_respects_language": True,
                "analytics_by_language": True,
                "tone_matrix_by_language": True,
                "native_voice_by_language": True,
            },
            "voice": {
                "transcription": True,
                "intent_from_audio": True,
                "text_or_audio_response": True,
                "operator_summary": True,
                "urgency_and_emotion": True,
                "tone_of_voice_detection": True,
                "context_from_vox": True,
                "use_voice_context_in_replies": True,
                "voice_memory_window": 3,
                "vox_context_priority": ["summary", "detected_language", "intent", "urgency_level", "emotion"],
            },
        },
        "vertical_context": {
            "id": profile["id"],
            "name": profile["name"],
            "short_name": profile["short_name"],
            "problem": profile["problem"],
            "portfolio_tier": profile.get("portfolio_tier"),
            "master_thesis": profile.get("master_thesis"),
            "recommended_integrations": profile.get("recommended_integrations", []),
            "objects": profile.get("objects", []),
            "flows": profile.get("flows", []),
            "kpis": profile.get("kpis", []),
            "buyer": deepcopy(profile.get("buyer", {})),
            "one_pager": deepcopy(profile.get("one_pager", {})),
            "demo_flow": deepcopy(profile.get("demo_flow", [])),
            "native_objects": deepcopy(profile.get("native_objects", {})),
            "pipeline": deepcopy(profile.get("pipeline", {})),
            "bot_playbook": deepcopy(profile.get("bot_playbook", {})),
            "automation_sequences": deepcopy(profile.get("automation_sequences", [])),
            "dashboard": deepcopy(profile.get("dashboard", {})),
            "hardening_model": deepcopy(profile.get("hardening_model", {})),
            "specialist_layers": deepcopy(profile.get("specialist_layers", {})),
            "domain_contract": deepcopy(profile.get("domain_contract", {})),
            "vertical_runtime": deepcopy(profile.get("vertical_runtime", {})),
            "transactional_motor_v12": deepcopy(profile.get("transactional_motor_v12", {})),
            "subvertical_playbooks": deepcopy(profile.get("subvertical_playbooks", [])),
            "business_e2e_tests": deepcopy(profile.get("business_e2e_tests", [])),
        },
        "behavior_settings": deepcopy(profile.get("behavior", {})),
        "response_templates": deepcopy(profile.get("templates", [])),
    }


def build_organization_settings(value: str | None, *, organization_name: str | None = None) -> dict[str, Any]:
    profile = get_vertical_profile(value)
    return {
        "vertical_profile": {
            "id": profile["id"],
            "name": profile["name"],
            "short_name": profile["short_name"],
            "description": profile["description"],
            "problem": profile["problem"],
            "portfolio_tier": profile.get("portfolio_tier"),
            "master_thesis": profile.get("master_thesis"),
            "subverticals": profile.get("subverticals", []),
            "recommended_integrations": profile.get("recommended_integrations", []),
            "one_pager": deepcopy(profile.get("one_pager", {})),
        },
        "launch_readiness": {
            "organization_name": organization_name or "",
            "backend": ["bot defaults", "templates seed", "behavior seed"],
            "frontend": ["catalogo de verticales", "super admin surfaces", "portal cliente"],
            "production": ["whatsapp", "calendar", "payments", "crm"],
        },
    }
