from __future__ import annotations

import json
import pprint
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / 'frontend' / 'app' / 'legal' / 'legal-registry.ts'
DOCS_PUBLIC_DIR = ROOT / 'docs' / 'legal' / 'public'
SUBPROCESSORS_PATH = ROOT / 'docs' / 'legal' / 'metadata' / 'subprocessors.public.json'
FRONTEND_CONTENT_PATH = ROOT / 'frontend' / 'app' / 'legal' / 'legal-content.ts'
BACKEND_ASSETS_PATH = ROOT / 'backend' / 'app' / 'legal_assets.py'


def load_registry() -> tuple[str, str, list[dict[str, object]]]:
    text = REGISTRY_PATH.read_text(encoding='utf-8')
    owner_match = re.search(r'export const legalOwner = "([^"]+)";', text)
    product_match = re.search(r'export const legalProduct = "([^"]+)";', text)
    docs_match = re.search(r'export const publicLegalDocs: PublicLegalDoc\[\] = (\[.*\]);\s*$', text, re.S)
    if not owner_match or not product_match or not docs_match:
        raise RuntimeError('No se pudo parsear frontend/app/legal/legal-registry.ts')
    return owner_match.group(1), product_match.group(1), json.loads(docs_match.group(1))


def build_content_map(docs: list[dict[str, object]]) -> dict[str, str]:
    content_map: dict[str, str] = {}
    for doc in docs:
        slug = str(doc['slug'])
        filename = str(doc['filename'])
        content_map[slug] = (DOCS_PUBLIC_DIR / filename).read_text(encoding='utf-8')
    return content_map


def write_frontend_content(content_map: dict[str, str]) -> None:
    FRONTEND_CONTENT_PATH.write_text(
        "// Generated by scripts/sync_legal_assets.py. Do not edit manually.\n"
        "export const publicLegalContent: Record<string, string> = "
        + json.dumps(content_map, ensure_ascii=False, indent=2)
        + " as const;\n",
        encoding='utf-8',
    )


def write_backend_assets(owner: str, product: str, docs: list[dict[str, object]], content_map: dict[str, str], subprocessors: dict[str, object]) -> None:
    payload = (
        "# Generated by scripts/sync_legal_assets.py. Do not edit manually.\n"
        "from __future__ import annotations\n\n"
        f"LEGAL_OWNER = {owner!r}\n"
        f"LEGAL_PRODUCT = {product!r}\n"
        "PUBLIC_LEGAL_DOCS = " + pprint.pformat(docs, width=120, sort_dicts=False) + "\n"
        "PUBLIC_LEGAL_CONTENT = " + pprint.pformat(content_map, width=120, sort_dicts=False) + "\n"
        "SUBPROCESSORS_PUBLIC = " + pprint.pformat(subprocessors, width=120, sort_dicts=False) + "\n"
    )
    BACKEND_ASSETS_PATH.write_text(payload, encoding='utf-8')


def main() -> None:
    owner, product, docs = load_registry()
    content_map = build_content_map(docs)
    subprocessors = json.loads(SUBPROCESSORS_PATH.read_text(encoding='utf-8'))
    write_frontend_content(content_map)
    write_backend_assets(owner, product, docs, content_map, subprocessors)
    print(f'[ok] synced {len(docs)} legal docs')


if __name__ == '__main__':
    main()
