from __future__ import annotations
def detect_vertical(text: str, override: str|None=None) -> dict:
    low=text.lower(); vertical=override or ("dental" if any(w in low for w in ["dental","dentista","ortodoncia"]) else "fitness" if any(w in low for w in ["gym","fitness","membres"]) else "generic_service")
    return {"vertical_id":vertical,"subvertical":"clinic" if vertical=="dental" else None,"primary_objective":"agendar" if "agenda" in low or vertical=="dental" else "vender","confidence":0.82}
def build_vertical_intelligence_pack(profile: dict, intensity: str="balanced") -> dict:
    vertical=profile.get("vertical_id","generic_service")
    pack={"vertical_id":vertical,"subvertical":profile.get("subvertical"),"business_model":"local_service","primary_objective":profile.get("primary_objective","agendar"),"customer_intents":["precio","horario","agendar","humano","soporte"],"high_value_intents":["agendar","comprar","pagar"],"risk_intents":["urgencia","promesa prohibida","precio exacto no confirmado"],"booking_logic":{"requires_confirmation":True},"sales_logic":{"never_invent_discounts":True},"support_logic":{"grounding_required":True},"collection_logic":{"frequency_caps":True},"retention_logic":{},"recovery_logic":{},"required_facts":["precios reales","horarios reales","destino humano","zona de cobertura"],"prohibited_claims":["resultados garantizados","certificaciones no confirmadas"],"escalation_rules":["pide humano","riesgo médico/legal","queja seria"],"qualification_questions":["¿Qué servicio necesitas?","¿Qué horario prefieres?","¿Es una urgencia?"],"objection_handlers":["precio depende de valoración confirmada","puedo explicarte opciones y pasarte con humano"],"recommended_tools":["book_appointment","handoff_to_human","tag_contact"],"recommended_templates":["appointment_confirmation","lead_reactivation","no_response_followup"],"required_knowledge_sources":["sitio web","FAQ","lista de precios","políticas"],"go_live_risks":["precios sin confirmar","handoff no configurado"]}
    if vertical=="dental": pack.update({"prohibited_claims":["diagnóstico médico","recetar medicamentos","resultados dentales garantizados"],"escalation_rules":["dolor fuerte","sangrado","embarazo","trauma","pide humano"],"qualification_questions":["¿Qué molestia o servicio necesitas?","¿Tienes dolor fuerte o sangrado?","¿Qué horario prefieres para valoración?"]})
    if vertical=="fitness": pack.update({"prohibited_claims":["resultado físico garantizado"],"escalation_rules":["lesiones","condición médica","pide humano"]})
    return pack
