from __future__ import annotations
from typing import Protocol
class CalendarProvider(Protocol):
    def build_oauth_url(self, conn, integration: dict) -> dict: ...
class PaymentsProvider(Protocol):
    def reconcile_pending(self, conn, *, organization_id: str | None = None, bot_id: str | None = None) -> dict: ...
class MetaProvider(Protocol):
    def start_embedded_signup(self, conn, *, organization_id: str, bot_id: str | None = None) -> dict: ...
class SSOProvider(Protocol):
    def build_authorization_url(self, conn, provider: dict) -> dict: ...
